### ISSUE TITLE
SVG support

### ISSUE THREAD

**Issue by sebdeckers** [gruntjs/grunt-contrib-imagemin#103]
I see that @sindresorhus has created a Grunt task to minify SVG files with [SVGO](https://github.com/svg/svgo).

Repo: https://github.com/sindresorhus/grunt-svgmin

Is there anything blocking svgmin from being added to imagemin? I'd be happy to take a look at it.

**Comment by EdwardBeckett** [comment]
No disrespect here but `image/svg-xml` is a recognized [image media type](http://www.w3.org/TR/SVG/mimereg.html) by the W3C.
