### ISSUE TITLE
grunt-contrib-imagemin install fails on windows 8

### ISSUE THREAD

**Issue by Crowdopolis** [gruntjs/grunt-contrib-imagemin#109]
npm install grunt-contrib-imagemin -g

Fails windows 8 x64

npm v 1.3.11
node v0.10.21
grunt v0.4.1 

npm install grunt-contrib-imagemin -g

npm http GET http://registry.npmjs.org/grunt-contrib-imagemin
npm http 304 http://registry.npmjs.org/grunt-contrib-imagemin
npm http GET http://registry.npmjs.org/jpegtran-bin
npm http GET http://registry.npmjs.org/filesize
npm http GET http://registry.npmjs.org/gifsicle
npm http GET http://registry.npmjs.org/optipng-bin
npm http GET http://registry.npmjs.org/pngquant-bin
npm http GET http://registry.npmjs.org/chalk
npm http 304 http://registry.npmjs.org/filesize
npm http 304 http://registry.npmjs.org/jpegtran-bin
npm http 304 http://registry.npmjs.org/optipng-bin
npm http 304 http://registry.npmjs.org/gifsicle
npm http 304 http://registry.npmjs.org/pngquant-bin
npm http 304 http://registry.npmjs.org/chalk
npm http GET http://registry.npmjs.org/ansi-styles
npm http GET http://registry.npmjs.org/has-color
npm http GET http://registry.npmjs.org/bin-wrapper
npm http 304 http://registry.npmjs.org/ansi-styles
npm http 304 http://registry.npmjs.org/bin-wrapper
npm http 304 http://registry.npmjs.org/has-color
npm http GET http://registry.npmjs.org/download
npm http GET http://registry.npmjs.org/isbin/0.0.2
npm http GET http://registry.npmjs.org/mout
npm http GET http://registry.npmjs.org/progress
npm http GET http://registry.npmjs.org/which
npm http 304 http://registry.npmjs.org/download
npm http 304 http://registry.npmjs.org/mout
npm http 304 http://registry.npmjs.org/which
npm http 304 http://registry.npmjs.org/isbin/0.0.2
npm http 304 http://registry.npmjs.org/progress
npm http GET http://registry.npmjs.org/mkdirp
npm http GET http://registry.npmjs.org/decompress
npm http GET http://registry.npmjs.org/through2
npm http GET http://registry.npmjs.org/async-foreach
npm http GET http://registry.npmjs.org/request
npm http GET http://registry.npmjs.org/async/0.1.22
npm http 304 http://registry.npmjs.org/mkdirp
npm http 304 http://registry.npmjs.org/through2
npm http 304 http://registry.npmjs.org/request
npm http 304 http://registry.npmjs.org/async-foreach
npm http 304 http://registry.npmjs.org/decompress
npm http 304 http://registry.npmjs.org/async/0.1.22
npm http GET http://registry.npmjs.org/adm-zip
npm http GET http://registry.npmjs.org/rimraf
npm http GET http://registry.npmjs.org/stream-combiner
npm http GET http://registry.npmjs.org/tar
npm http GET http://registry.npmjs.org/temp
npm http GET http://registry.npmjs.org/xtend
npm http GET http://registry.npmjs.org/readable-stream
npm http 304 http://registry.npmjs.org/adm-zip
npm http 304 http://registry.npmjs.org/stream-combiner
npm http 304 http://registry.npmjs.org/temp
npm http 304 http://registry.npmjs.org/rimraf
npm http 304 http://registry.npmjs.org/tar
npm http 304 http://registry.npmjs.org/xtend
npm http 304 http://registry.npmjs.org/readable-stream
npm http GET http://registry.npmjs.org/duplexer
npm http GET http://registry.npmjs.org/graceful-fs
npm http GET http://registry.npmjs.org/is-object
npm http GET http://registry.npmjs.org/object-keys
npm http GET http://registry.npmjs.org/osenv/0.0.3
npm http 304 http://registry.npmjs.org/duplexer
npm http 304 http://registry.npmjs.org/graceful-fs
npm http 304 http://registry.npmjs.org/object-keys
npm http 304 http://registry.npmjs.org/is-object
npm http 304 http://registry.npmjs.org/osenv/0.0.3
npm WARN deprecated object-keys@0.2.0: Please update to the latest object-keys
npm http GET http://registry.npmjs.org/indexof
npm http GET http://registry.npmjs.org/foreach
npm http GET http://registry.npmjs.org/is
npm http 304 http://registry.npmjs.org/indexof
npm http 304 http://registry.npmjs.org/is
npm http 304 http://registry.npmjs.org/foreach
npm http GET http://registry.npmjs.org/inherits
npm http GET http://registry.npmjs.org/block-stream
npm http GET http://registry.npmjs.org/fstream
npm http 304 http://registry.npmjs.org/fstream
npm http 304 http://registry.npmjs.org/block-stream
npm http 304 http://registry.npmjs.org/inherits
npm http GET http://registry.npmjs.org/forever-agent
npm http GET http://registry.npmjs.org/tunnel-agent
npm http GET http://registry.npmjs.org/http-signature
npm http GET http://registry.npmjs.org/aws-sign
npm http GET http://registry.npmjs.org/oauth-sign
npm http GET http://registry.npmjs.org/node-uuid
npm http GET http://registry.npmjs.org/cookie-jar
npm http GET http://registry.npmjs.org/form-data
npm http GET http://registry.npmjs.org/mime
npm http GET http://registry.npmjs.org/qs
npm http GET http://registry.npmjs.org/json-stringify-safe
npm http GET http://registry.npmjs.org/hawk
npm http 304 http://registry.npmjs.org/http-signature
npm http 304 http://registry.npmjs.org/forever-agent
npm http 304 http://registry.npmjs.org/oauth-sign
npm http 304 http://registry.npmjs.org/tunnel-agent
npm http 304 http://registry.npmjs.org/aws-sign
npm http 304 http://registry.npmjs.org/node-uuid
npm http 304 http://registry.npmjs.org/form-data
npm http 304 http://registry.npmjs.org/cookie-jar
npm http 304 http://registry.npmjs.org/mime
npm http 304 http://registry.npmjs.org/qs
npm http 304 http://registry.npmjs.org/json-stringify-safe
npm http 304 http://registry.npmjs.org/hawk
npm http GET http://registry.npmjs.org/combined-stream
npm http GET http://registry.npmjs.org/async
npm http 304 http://registry.npmjs.org/async
npm http GET http://registry.npmjs.org/assert-plus/0.1.2
npm http GET http://registry.npmjs.org/asn1/0.1.11
npm http GET http://registry.npmjs.org/ctype/0.5.2
npm http 304 http://registry.npmjs.org/combined-stream
npm http 304 http://registry.npmjs.org/asn1/0.1.11
npm http 304 http://registry.npmjs.org/ctype/0.5.2
npm http 304 http://registry.npmjs.org/assert-plus/0.1.2
npm http GET http://registry.npmjs.org/delayed-stream/0.0.5
npm http 304 http://registry.npmjs.org/delayed-stream/0.0.5
npm http GET http://registry.npmjs.org/boom
npm http GET http://registry.npmjs.org/cryptiles
npm http GET http://registry.npmjs.org/hoek
npm http GET http://registry.npmjs.org/sntp
npm http 304 http://registry.npmjs.org/sntp
npm http 304 http://registry.npmjs.org/cryptiles
npm http 304 http://registry.npmjs.org/boom
npm http 304 http://registry.npmjs.org/hoek

> gifsicle@0.1.4 postinstall 
> ...\npm\node_modules\grunt-contrib-imagemin\node_modules\gifsicle
> node lib/check.js
> 
> jpegtran-bin@0.2.1 postinstall C:\Users\Mopholo\AppData\Roaming\npm\node_modules\grunt-contrib-imagemin\node_modules\jpegtran-bin
> node lib/check.js

  gifsicle.exe: downloading [====               ] 25% 0.2s

> optipng-bin@0.3.1 postinstall C:\Users\Mopholo\AppData\Roaming\npm\node_modules\grunt-contrib-imagemin\node_modules\optipng-bin
> node lib/check.js

  gifsicle.exe: downloading [===================] 100% 0.0s

√ pre-build test passed successfully
  libjpeg-62.dll: downloading [===                ] 18% 0.2s

> pngquant-bin@0.1.5 postinstall C:\Users\Mopholo\AppData\Roaming\npm\node_modules\grunt-contrib-imagemin\node_modules\pngquant-bin
> node lib/check.js

  libjpeg-62.dll: downloading [===================] 100% 0.0s

  libjpeg-62.dll: downloading [=====              ] 28% 0.7s? pre-build test failed, compiling from source...

C:\Users\Mopholo\AppData\Roaming\npm\node_modules\grunt-contrib-imagemin\node_modules\jpegtran-bin\lib\check.js:19
                        throw new Error('building is not supported on ' + process.platform);
                              ^
Error: building is not supported on win32
    at C:\Users\Mopholo\AppData\Roaming\npm\node_modules\grunt-contrib-imagemin\node_modules\jpegtran-bin\lib\check.js:19:10
    at ChildProcess.<anonymous> (C:\Users\Mopholo\AppData\Roaming\npm\node_modules\grunt-contrib-imagemin\node_modules\jpegtran-bin\node_modules\bin-wrapper\bin-wrapper.js:168:16)
    at ChildProcess.EventEmitter.emit (events.js:95:17)
    at Process.ChildProcess._handle.onexit (child_process.js:787:12)

module.js:340
    throw err;
          ^
Error: Cannot find module 'chalk'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (C:\Users\Mopholo\AppData\Roaming\npm\node_modules\grunt-contrib-imagemin\node_modules\optipng-bin\lib\check.js:4:13)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)

module.js:340
    throw err;
          ^
Error: Cannot find module 'chalk'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (C:\Users\Mopholo\AppData\Roaming\npm\node_modules\grunt-contrib-imagemin\node_modules\pngquant-bin\lib\check.js:4:13)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
npm ERR! weird error 8
npm ERR! not ok code 0

C:\Users\Mopholo>npm install grunt-contrib-imagemin -g

**Comment by davewallace** [comment]
Experiencing what appears to be the same issue on WIndows 10 on one machine, but not another, where both machines have had mostly identical setups; nvm, a handful of global installed packages like grunt-cli and jshint. I checked the working `npm install` (https://github.com/tastejs/todomvc/ clone) and the package.json contains: `"gulp-imagemin": "1.0.0",`. 

In this gist you can see the console output for the failed Windows 10 `npm install`: https://gist.github.com/davewallace/3bef739c5a4957b087db28a0c3bd00b4

When I search for `imagemin` in that output, I see different version numbers for things, not sure if that relates to some comments above about increasing version numbers:

```
+-- gulp-imagemin@1.0.0
...
| +-- imagemin@0.4.9
```

On both Windows 10 boxes I am cloned and running `npm install` on the same todo-mvc repo mentioned above.

**Comment by davewallace** [comment]
In a reduced test case, I just ran `npm install pngquant-bin@0.3.5`, `npm install optipng-bin@0.3.11` , `npm install gifsicle@0.1.7` and `npm install jpegtran-bin@0.2.8` (with elevated privileges) in an empty directory, and all of them generated the same flavour of error:
```
> node index.js

path.js:7
    throw new TypeError('Path must be a string. Received ' + inspect(path));
    ^

TypeError: Path must be a string. Received { url: 'https://raw.github.com/imagemin/optipng-bin/v0.3.11/vendor/win/optipng.exe',
  name: 'optipng.exe',
  os: 'win32' }
    at assertPath (path.js:7:11)
    at Object.basename (path.js:801:5)
    at C:\wamp\www\codefinger-projects\prototypes\test\node_modules\download\index.js:35:43
    at each (C:\wamp\www\codefinger-projects\prototypes\test\node_modules\each-async\each-async.js:63:4)
    at module.exports (C:\wamp\www\codefinger-projects\prototypes\test\node_modules\download\index.js:33:5)
    at C:\wamp\www\codefinger-projects\prototypes\test\node_modules\bin-wrapper\index.js:108:20
    at C:\wamp\www\codefinger-projects\prototypes\test\node_modules\bin-wrapper\index.js:141:24
    at C:\wamp\www\codefinger-projects\prototypes\test\node_modules\bin-check\index.js:30:20
    at C:\wamp\www\codefinger-projects\prototypes\test\node_modules\executable\index.js:39:20
    at FSReqWrap.oncomplete (fs.js:117:15)
```

This issue is definitely still alive and rebelling.

**Comment by hem-kant** [comment]
@davewallace ,Yes this isse is still alive 
![image](https://user-images.githubusercontent.com/13075832/28529062-1eec6966-70ad-11e7-9384-a0dbc953dc73.png)

**Comment by jorrit** [comment]
Why aren't you running `npm install grunt-contrib-imagemin`?

**Comment by hem-kant** [comment]
@jorrit `npm install jpegtran-bin@0.2.3`
