### ISSUE TITLE
Running "imagemin:dynamic" (imagemin) task Fatal error: spawn EACCES

### ISSUE THREAD

**Issue by ShaneSheppard** [gruntjs/grunt-contrib-imagemin#164]
I have imagemin taking images from assets/img to a folder named _site/img,
it works perfectly when there are no images in assets/img but as soon as it has images to minify the above error displays in the command line.
However what's even more strange as this error never displays or occurs on a windows computer.

Had a look online for this error but can't seem to find much on it when it comes to grunt-contrib-imagemin, can anyone help me with this as it works perfectly otherwise?

**Comment by Strajk** [comment]
For those who arrive here from google as myself:

Upgrading from 0.8.1 to 0.9.3 fixed the issue for me... explanation here https://github.com/gruntjs/grunt-contrib-imagemin/issues/252#issuecomment-60462213
