### ISSUE TITLE
Fatal error: Cannot read property 'contents' of undefined

### ISSUE THREAD

**Issue by ravitadi** [gruntjs/grunt-contrib-imagemin#208]
By placing src: ['*_/_'] for dyamic imagemin
it throws Fatal error: Cannot read property 'contents' of undefined.

I am trying to min all the images in a folder which has additional folders containing imgs inside of it.
This issue only happens if a folder exists inside of a folder.

**Comment by andycao** [comment]
thank you all, i encounter the same problem and solved by reinstall grunt-contrib-imagemin

**Comment by corgrath** [comment]
I am getting this problem now with the latest version, version 3.2.2.

I have tried to remove all npm packages and reinstall without luck.

**Comment by michal-husak** [comment]
@corgrath try to update to new version 1.0.0: "grunt-contrib-imagemin": "^1.0.0"
now it works for me

**Comment by naoyeye** [comment]
`npm cache clean && npm install grunt-contrib-imagemi`

it's works for me

thanks @kevva.

**Comment by moses-seeq** [comment]
I agree with @michal-husak.  Referencing the last version, even with a ~ failed.  However, when I updated my package.json to 1.0.0, it works.

**Comment by corgrath** [comment]
Awesome. I was previously on grunt-contrib-imagemin version 0.9.4, but had the latest imagemin 3.2.2.

Everything works, thanks guys!

**Comment by dubane** [comment]
FYI - We started having the exact same problem a couple days ago too. I'm not sure why our previous builds that were using imagemin 0.9.4 suddenly started breaking but my best guess is that's it related to this: https://github.com/gruntjs/grunt-contrib-imagemin/commit/33525988bad99b498208360d51f34da512b23507 where grunt-contrib-imagemin was updated from 0.9.4 to 1.0.0

For us changing our package.json file to 1.0.0 also solved the issue just like it did for others.

**Comment by adambarthelson** [comment]
+1 for ```1.0.0```

**Comment by giovannipds** [comment]
:+1: for 1.0.0 heres too.

**Comment by elenatorro** [comment]
Solved using 1.0.0 too :)

**Comment by maslick** [comment]
1.0.0 is the winner

**Comment by idawave** [comment]
+1 for 1.0.0.
Still, I was using 0.9.3, is the fix merged to it too?

**Comment by MaxFlower** [comment]
npm cache clean && npm install grunt-contrib-imagemi

it's works for me too. Thanks for all.

**Comment by JacobH1992** [comment]
+1 for ```1.0.0.```

had to ```npm install grunt-contrib-imagemin --save-dev``` again though

**Comment by leeder** [comment]
+1 for 1.0.0.

**Comment by kzanev** [comment]
+1 for 1.0.0.

**Comment by vladyn** [comment]
Thanks for the answers guys! It worked by upgrading the imagemin

**Comment by vidstige** [comment]
+1 for 1.0.0

**Comment by vidstige** [comment]
However, the packaging of `grunt-contrib-imagemin` is broken, the latest and greatest of this should have   cap of the version supported.

**Comment by brunomptorres** [comment]
+1 for 1.0.0

**Comment by zoltanradics** [comment]
+1 for 1.0.0

**Comment by irisSchaffer** [comment]
+1 for 1.0.0

**Comment by wchid** [comment]
+1 for
    npm cache clean && npm install grunt-contrib-imagemin
thanks @kevva.

**Comment by MattSich** [comment]
+1 for 1.0.0

**Comment by R4YM3** [comment]
+1 for 1.0.0

**Comment by idothebest4u** [comment]
+1 for 1.0.0..thanks much..saved my time

**Comment by xfg** [comment]
+1 for 1.0.0.

**Comment by vinnybad** [comment]
1.0.0 fixes the issue!

**Comment by ryanburnett** [comment]
Thanks @kevva

**Comment by antweiss** [comment]
Upgrading grunt-contrib-imagemin to 1.0.0 solved this for us 3 months ago but today we suddenly got the same error message again! My guess is that something in dependency versions has changed but  we failed to find what that is. Any help or advice will be much appreciated.

**Comment by benurb** [comment]
Confirmed. It seems the problem is caused by this commit in the vinyl-fs dependency https://github.com/gulpjs/vinyl-fs/commit/d21ee0908fe3541178d8f58957a31906def4907b

**Comment by landru29** [comment]
Yes, vinyl-fs broke since version 2.3.0 !

**Comment by benurb** [comment]
You could also temporarily add this to your package.json:
```json
"scripts": {
    "postinstall": "cd node_modules/grunt-contrib-imagemin/node_modules/imagemin && rm -rf node_modules/vinyl-fs && npm i vinyl-fs@2.2.x"
  }
```

**Comment by benurb** [comment]
I created a PR in vinyl-fs, that should fix this problem.
https://github.com/gulpjs/vinyl-fs/pull/142
Let's see how they think about it :smile:

**Comment by hypery2k** [comment]
@benurb can confirm that's working for me. Thanks

**Comment by stedda** [comment]
In task-runner on src u don't need the `{}` anymore.
Please replace the src like this : ` src: '[*/*.{png,jpg,jpeg,gif,svg}]'`, and put the path and specific images. 
For me that worked.

**Comment by sebastian-marinescu** [comment]
@benurb Thanks, this worked for me, after adapting it for **Windows**:

```javascript    
"scripts": {
    "postinstall": "cd node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules && del /F /Q vinyl-fs && cd.. && npm install vinyl-fs@2.2.x"
}
```

**Comment by mmautner** [comment]
+1

**Comment by floydpink** [comment]
@benurb -
> For npm 3 you can use a partial shrinkwrap.

Could you please explain how I can do 'a partial shrinkwrap' to solve this issue for npm 3?

**Comment by revof11** [comment]
+1

**Comment by RemeJuan** [comment]
Upgrading to 1.0 and following @stedda's suggestion it is working for me.

**Comment by alanshortis** [comment]
As @RemeJuan - upgrading to 1.0.0 and following @stedda 's suggestion is what finally fixed it for me.

**Comment by gskachkov** [comment]
@stedda Thanks for solution!

**Comment by stephenweaver** [comment]
@stedda Thanks!

**Comment by lpsBetty** [comment]
@stedda  what exactly do I have to change? 

from
````
src: '{,*/}*.{png,jpg,jpeg,gif}',
````
to
````
src: '*/*.{png,jpg,jpeg,gif}',
````
?

**Comment by samhax** [comment]
@stedda Thanks!!!

@lpsBetty you're almost there, you're missing [ ] 
 '[*/*.{png,jpg,jpeg,gif,svg}]'

**Comment by TanKucukhas** [comment]
Adding 
'"scripts": {
    "postinstall": "cd node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules && del /F /Q vinyl-fs && cd.. && npm install vinyl-fs@2.2.x"
}' 
on the package.json than 'npm install' fixed the problem for me. Thanks for the solution.

**Comment by TanKucukhas** [comment]
Adding the code to package.json
`"scripts": {
    "postinstall": "cd node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules && del /F /Q vinyl-fs && cd.. && npm install vinyl-fs@2.2.x"
}`
than `npm install` fixed the problem for me. Thanks for the solution.

**Comment by altendo** [comment]
confirmed that adding the postinstall script mentioned by @benurb and @TanKucukhas works (manually ran the command but should work fine as a postinstall script).

**Comment by lvarayut** [comment]
Thanks @benurb. It worked like a charm!

**Comment by lpsBetty** [comment]
@stedda @samhax hmm I really have problems getting it working!

it works locally (but NOT on the CI server) with this:
````
    imagemin: {
      dist: {
        files: [{
          expand: true,
          cwd: '<%= yeoman.app %>/images',
          src: '**/*.{png,jpg,jpeg,gif}',
          dest: '<%= yeoman.dist %>/images'
        }]
      }
    },
````
and when I add ``[]`` inside the src `` '[**/*.{png,jpg,jpeg,gif}]'`` it doesn't copy all images from the wd to destination directory.. but it would work on the CI

**Comment by stedda** [comment]
@ipsBetty have you checked if the files are not corupted by git or repo when you upload them ? You should also check you're `.gitattributes` file and check the binary files. You should also add in you're file the following code if it's missing: 
`
*.png  binary
*.jpg  binary
*.jpeg binary
*.gif  binary
*.ico  binary
`
.Let me know if this might have been the problem.

**Comment by lpsBetty** [comment]
@stedda it worked before all the time, so I don't think my files are corrupted.. I think it has something to do with the change of ``vinyl-fs``

**Comment by lpsBetty** [comment]
... ah sorry I found the problem.. svgmin also used ``{}`` 

thanks again for the solution :)

**Comment by threxx** [comment]
So I still have this error and i definitely don't know what to do anymore. My imagemin is this:
```     imagemin: {
      dist: {
        files: [{
          expand: true,
          cwd: '<%= yeoman.app %>/images',
          src: '[*/*.{png,jpg,jpeg,gif}]',
          dest: '<%= yeoman.dist %>/images'
        }]
      }
    }, ```

Also tried to add this npm script, but that doesn't work either, as I get the following error:
``` sh: line 0: cd: node_modules/grunt-contrib-imagemin/node_modules/imagemin: No such file or directory```. Anyone knows what to do?

**Comment by mdavidcu** [comment]
+1 for 1.0.0 version

**Comment by Dr-Sun** [comment]
@stedda Thanks!

**Comment by nottinhill** [comment]
@samhax answer worked for me for both svgmin and imgmin Grunt Tasks.

**Comment by micho8402** [comment]
+1 for 1.0.0

**Comment by jivasquez** [comment]
Thanks!

**Comment by steelx** [comment]
solution
`"grunt-contrib-imagemin": "^1.0.0",`
