### ISSUE TITLE
0.7.0 crash on linux

### ISSUE THREAD

**Issue by lcalvy** [gruntjs/grunt-contrib-imagemin#215]
Hi, 

Codeship CI is failing on 0.0.7 package with error : 
Running "imagemin:dist" (imagemin) task
Verifying property imagemin.dist exists in config...OK
Files: core/public/assets/img/content/illustrations/author.png -> dist-digital/public/assets/img/content/illustrations/author.png
Files: core/public/assets/img/content/illustrations/user.png -> dist-digital/public/assets/img/content/illustrations/user.png
Files: core/public/assets/img/content/illustrations/user_default.png -> dist-digital/public/assets/img/content/illustrations/user_default.png
Files: core/public/assets/img/content/illustrations/video_thumb.jpg -> dist-digital/public/assets/img/content/illustrations/video_thumb.jpg
Files: core/public/assets/img/content/illustrations/winnerHead.jpg -> dist-digital/public/assets/img/content/illustrations/winnerHead.jpg
Options: interlaced, optimizationLevel=3, progressive
Warning: spawn ENOENT Use --force to continue.

**Comment by mahanare** [comment]
```
Harinath:yo harinath$ grunt imagemin
Running "imagemin:dist" (imagemin) task
Fatal error: Cannot read property 'contents' of undefined
````


I see this error. I know this thread is older one but any suggestions on what can fix this error?

**Comment by vladikoff** [comment]
> I see this error. I know this thread is older one but any suggestions on what can fix this error? 

update to 1.0.0

**Comment by mahanare** [comment]
worked, thank you @vladikoff

**Comment by derek-adair** [comment]
I got this running the base yo angular project in debian.
