### ISSUE TITLE
Missing 'imagemin-gifsicle' module error when executing imagemin

### ISSUE THREAD

**Issue by Danilux** [gruntjs/grunt-contrib-imagemin#228]
Just installed imagemin on Windows 7 but I'm getting this error, any light on this? Thanks.

Loading "imagemin.js" tasks...ERROR

> > Error: Cannot find module 'imagemin-gifsicle'

Warning: Task "imagemin" not found. Use --force to continue.

**Comment by arafath-mk** [comment]
I had same issue. It is solved when "grunt-contrib-imagemin" version is changed as below. (in the root package.json)
"grunt-contrib-imagemin": "^0.9.2"

**Comment by kaelle** [comment]
@madhead that worked for me as well, thanks!

**Comment by wutangpaul** [comment]
@madhead Thanks for the fix.

**Comment by lremurphy** [comment]
@madhead Thank you so much this worked for me as well
