### ISSUE TITLE
Fatal error: This socket is closed.

### ISSUE THREAD

**Issue by maraisr** [gruntjs/grunt-contrib-imagemin#273]
So this morning for some bizarre reason this issue seems to only occur with this task. node v0.10.33 If i copy in the folder "grunt-contrib-imagemin" from another working project it seems to work fine, so i think its just when i went npm update --save-dev this morning that it messed things up.

**Comment by davetgreen** [comment]
I've been trying to include imagemin in our boilerplate at work and there never seems to be a build that works on Win7. I'm having the same issue and considering throwing myself out of the window. :)

**Comment by kevva** [comment]
Use 0.9.2.

**Comment by GomesNayagam** [comment]
getting same error with 0.9.2

**Comment by GomesNayagam** [comment]
worked this way : npm install grunt-contrib-imagemin@0.9.2 --save-dev

**Comment by blowsie** [comment]
@Saturn2888 The deep folders are no problem to delete with `npm uninstall`

**Comment by vicky-gonsalves** [comment]
+1 @recchi
