### ISSUE TITLE
can't optimize images  the output always "Minified xxx images (saved 0 B)"

### ISSUE THREAD

**Issue by dashixiong** [gruntjs/grunt-contrib-imagemin#276]
here is my settings:
module.exports = function (grunt) {
    grunt.initConfig({
        imagemin: 
            dist: {
                options: {
                    optimizationLevel: 3
                },
                files: [{
                    expand: true,
                    cwd: 'img/',
                    src: ['*_/_.{png,jpg,jpeg}'],
                    dest: 'images/' 
                }]
            }
        },
    });
    grunt.loadNpmTasks('grunt-contrib-imagemin');
    grunt.registerTask('img', ['imagemin']);
};

my output:
Minified 8 images (saved 0 B)

I change many images  without error  but always save 0b

![image](https://cloud.githubusercontent.com/assets/3839754/5499553/ec9d9e20-876c-11e4-9974-a012769f0422.png)

**Comment by amiroo-webdeveloper** [comment]
How you resolve it?

**Comment by johngeoffrey** [comment]
Was this resolved or just closed??

**Comment by maboiteaspam** [comment]
maybe they are yet already resolved.
Give it a try with the fixtures files there : https://github.com/gruntjs/grunt-contrib-imagemin/tree/master/test/fixtures

**Comment by wilmoth77** [comment]
I'm having the same issue.

Here are my settings in grunt:

imagemin: {
     dynamic: {
         options: {
             optimizationLevel: 7,
         },
        files: [{
            expand: true,
            cwd: './assets/img/',
            src: ['**/*.{png,jpg,gif,ico}'],
            dest:'./public/img/'
        }]
      }
    },

Here is my output:

$ grunt imagemin
Running "imagemin:dynamic" (imagemin) task
Minified 3 images (saved 0 B)

Done, without errors.
