### ISSUE TITLE
errors during installation

### ISSUE THREAD

**Issue by schel4ok** [gruntjs/grunt-contrib-imagemin#279]
I got error during imagemin installation
d:\OpenServer\domains\schel4ok.dev>npm install grunt-contrib-imagemin --save-dev
npm WARN engine imagemin@3.1.0: wanted: {"node":">=0.10.0","npm":">=2.1.5"} (current: {"node":"0.10.35","npm":"1.4.28"})

then I tried to upgrade npm

d:\OpenServer\domains\schel4ok.dev>npm install -g npm@latest
C:\Users\ilya.popov\AppData\Roaming\npm\npm -> C:\Users\ilya.popov\AppData\Roaming\npm\node_modules\npm\bin\npm-cli.js
npm@2.1.18 C:\Users\ilya.popov\AppData\Roaming\npm\node_modules\npm

but still have same error 

d:\OpenServer\domains\schel4ok.dev>npm install grunt-contrib-imagemin --save-dev

npm WARN engine imagemin@3.1.0: wanted: {"node":">=0.10.0","npm":">=2.1.5"} (current: {"node":"0.10.35","npm":"1.4.28"})

**Comment by vladikoff** [comment]
Seems like it still tried to use old npm `{"node":"0.10.35","npm":"1.4.28"})`

**Comment by sindresorhus** [comment]
Upgrade npm.
