### ISSUE TITLE
Unable to use grunt templates in dest path

### ISSUE THREAD

**Issue by treehousetim** [gruntjs/grunt-contrib-imagemin#280]
grunt.initConfig({
	pkg: grunt.file.readJSON('package.json'),
	buildPath: 'build/',
	imagemin: {
			dynamic: {
				files: [{
					expand: true,
					cwd: 'img/',
					src: ['**/*.{png,jpg,gif}'],
					dest: '<%= buildPath %>img'
				}]
			}
		},

This creates folders named <%= buildPath %>img instead of properly expanding the template.

**Comment by sindresorhus** [comment]
You're either doing something wrong or it's a grunt bug. This task is just using the [grunt API](https://github.com/gruntjs/grunt-contrib-imagemin/blob/e6350cf682a77cec393a85d39caa09d13ab178b4/tasks/imagemin.js#L21) to get the paths, which should handle this.
