### ISSUE TITLE
Build fails

### ISSUE THREAD

**Issue by SamVerschueren** [gruntjs/grunt-contrib-imagemin#281]
As you can see, the status if the build process fails.

**Comment by kevva** [comment]
Please, provide some info.

**Comment by SamVerschueren** [comment]
I mean the tests, sorry.

https://ci.appveyor.com/project/gruntjs/grunt-contrib-imagemin

**Comment by kevva** [comment]
It's because optipng fails to install. It works locally on Windows though.
