### ISSUE TITLE
Imagemin parameters are so confusing

### ISSUE THREAD

**Issue by glecoz** [gruntjs/grunt-contrib-imagemin#286]
After struggling for half an hour with the parameters and the doc (https://www.npmjs.com/package/grunt-contrib-imagemin), I finally found that :

* "cwd" parameter means "src_path"
* "src" => file and path patterns only
* "dest" => dest_path

Example :

    imagemin: {
            prod: {
                expand: true,
                cwd: '<%= assets_dev %>/images',      // src path
                src: ['**/*.{png,jpg,gif}'],         // file pattern only
                dest: '<%= assets_prod %>/images'    // dest path
            },
            options: {
                optimizationLevel: 3
            }
        }

**Comment by sindresorhus** [comment]
That's grunt and has nothing specifically to do with this plugin.

https://github.com/gruntjs/grunt-docs/issues/2
