### ISSUE TITLE
Ability to ignore default optimizers

### ISSUE THREAD

**Issue by shwetasingh** [gruntjs/grunt-contrib-imagemin#288]
Hi,

First of all, great grunt plugin!!  

I am using mozjpeg and pngquant optimizers (just because I saw better results in terms of compression ratio and speed). Is it possible to tell grunt-contrib-imagemin to not install jpegtran and optipng dependencies since I am not using it.

Thanks!

**Comment by kevva** [comment]
Currently, there's no way, no. They are dependencies of the `imagemin` package.
