### ISSUE TITLE
Fatal Error: imagemin:dist - client/images/yeogurt-swirl.png

### ISSUE THREAD

**Issue by KDCinfo** [gruntjs/grunt-contrib-imagemin#289]
Unsure whether to post this here, or on "generator-yeogurt" (due to the "yeogurt-swirl.png" image being referenced). Please advise if wrong. 

I just installed the yo yeogurt generator. When I did a "grunt build" I received the error shown below. I couldn't find anything on either Google or in the issues listed here, but again, maybe this belongs in the "generator-yeogurt" issues list...

Running "concurrent:images" (concurrent) task
    Warning: Running "imagemin:dist" (imagemin) task
    Warning: Error:
    #
    # Fatal error in ../deps/v8/src/heap/store-buffer.cc, line 132
    # CHECK(old_virtual_memory_->Commit(reinterpret_cast<void*>(old_limit_), grow * kPointerSize, false)) failed
    #
     in file client/images/yeogurt-swirl.png Use --force to continue.
    Aborted due to warnings.

**Comment by kevva** [comment]
This is not related to this module. Frankly, I've no idea where to look but this seems related https://github.com/joyent/node/issues/7746.
