### ISSUE TITLE
Handling .gif

### ISSUE THREAD

**Issue by kb19** [gruntjs/grunt-contrib-imagemin#29]
It doesn't seem like Imagemin is moving gifs over to the 'dest' directory. My task is as follows:

``` javascript
imagemin: {
    dist: {
        files: [{
          expand: true,
          cwd: '<%= yeoman.app %>/img',
          src: '{,*/}*.{png,jpg,jpeg,gif,webp}',
          dest: '<%= yeoman.dist %>/img'
        }]
      }
    }

```

**Comment by mrshannonyoung** [comment]
What was the resolve on this? Can we use it for GIFs? I don't see in the readme where it states it wont process GIFs.
