### ISSUE TITLE
imagemin warning?

### ISSUE THREAD

**Issue by myzhibie** [gruntjs/grunt-contrib-imagemin#290]
when I executed the imagemin task ,it showed me warnings in the below :
Warning: Error: Command failed:  in file app/images/spine.png Used --force, cont
inuing.
Warning: Error: Command failed:  in file app/images/timeline.png Used --force, c
ontinuing.
 and aborted the task.I found that two png images in my images directory caused this warning and in the later ,this task did not copy these two pngs even if I added --force parameter.It is strange that other pngs work well with this task. Can you tell me why or what I can do to avoid this situation？

**Comment by kevva** [comment]
Can you share the images?

**Comment by myzhibie** [comment]
![timeline](https://cloud.githubusercontent.com/assets/8846963/6914787/e29fd93e-d7c0-11e4-8c20-815ae9d2a770.png)
![spine](https://cloud.githubusercontent.com/assets/8846963/6914799/f533f2ce-d7c0-11e4-8bfc-faaf92a2c3f7.png)
These two  pngs did not work well.Thanks.

**Comment by adityadineshsaxena** [comment]
:+1:

**Comment by oak-tree** [comment]
We had the same issue. update it to the latest `image-min` version solved the problem
