### ISSUE TITLE
install fails with npm ERR! cb() never called!

### ISSUE THREAD

**Issue by gr2m** [gruntjs/grunt-contrib-imagemin#292]
I know the error message is not very helpful, but maybe others will google for it (as I did) and find their way here. 

My first guess was that I had `jpegtran` and `optipng` installed globally and there is a conflict, but even after removed these, I still get the same error. 

See the full log for `install gruntr-contrib-imagemin --verbose` here:
https://dl.dropboxusercontent.com/u/732913/npm-install-grunt-contrib-imagemin.txt.zip

**Comment by kevva** [comment]
https://github.com/sindresorhus/gulp-imagemin/issues/102
