### ISSUE TITLE
imagemin not minifying

### ISSUE THREAD

**Issue by TyBerry** [gruntjs/grunt-contrib-imagemin#296]
No matter what images I put in, imagemin will run but will always say Saved 0 B. I know this was working before in a different but older project. Maybe some update broke imagemin?

grunt --version
grunt-cli v0.1.13
grunt v0.4.5

npm --version
2.7.3

Output
===========
Running "imagemin:dist" (imagemin) task
Minified 8 images (saved 0 B)

Gruntfile
===========
imagemin: {
       dist: {
          options: {
            optimizationLevel: 7
          },
          files: [{
             expand: true,
             cwd: 'assets/imagemin/',
             src: ['**/*.{png,jpg,jpeg,gif}'],
             dest: 'assets/img/'
          }]
       }
    }

grunt.loadNpmTasks('grunt-contrib-imagemin');

grunt.registerTask('build', ['imagemin']);

**Comment by kevva** [comment]
Try reinstalling, nothing is broken as far as I know.

**Comment by TyBerry** [comment]
Thanks for the quick reply. I already tried reinstalling. I am setting this up for a new project and I don't think I've missed any steps. I know this has worked before so I'm confused as to why it seems to not be minifying anything now.

**Comment by kevva** [comment]
Did you get any messages upon installing?

**Comment by TyBerry** [comment]
So a couple more things, when I ran the imagemin even at optimizationLevel 7, it ran in like a second and returned the 0 B saved.

I downgraded npm  to version 2.5.1.

Now it takes 45 seconds to run and I'm getting this which is what I expect

Running "imagemin:dist" (imagemin) task
Minified 8 images (saved 180.32 kB)

So apparently imagemin does not play well with npm version 2.7.3? Can you test this when you have a chance?

**Comment by TyBerry** [comment]
I had no issues that I recall when I reinstalled imagemin. I don't have the output anymore. I think the issue may be with later versions of npm working with imagemin.
