### ISSUE TITLE
Optional dependencies for imagemin needs to be installed manually (or files gets copied instead of optimized)

### ISSUE THREAD

**Issue by erik-man** [gruntjs/grunt-contrib-imagemin#298]
This might only be a documentation issue, but I get the impression that grunt-contrib-imagemin should optimize images from a clean install, however instead it copies the files and reports that the images can't be optimized.

If I install the dependencies (imagemin-gifsicle, imagemin-jpegtran, imagemin-optipng, imagemin-svgo) manually then it works as expected (the dependencies are marked as optional in imagemin so they don't get installed by default).

Expected:
The dependencies to be installed automatically, or documentation should include how to install the dependencies (could also be nice if the output said 'no optimizier available' or similar when no suitable plugin is loaded).

**Comment by kevva** [comment]
@erik-man, they do get installed by default but `npm` won't exit if they fail to install (which they do sometimes).

**Comment by erik-man** [comment]
Yes, you were right :), turned out to be a problem with a npm-registry cache on my end which blocked them. Still I would like to add a feature request for printing something else than "already optimized" when no plugins have processed a file :)
