### ISSUE TITLE
PNG minifying

### ISSUE THREAD

**Issue by decibelnl** [gruntjs/grunt-contrib-imagemin#299]
When I try to minify my PNG images (For example my testing logo: 93.7 KB) it minify's it to 72.6 KB, but if I use the TinyPNG website it's reduced to 26.1 KB. I even set my optimizationLevel to 7 and tried different levels. How come the TinyPNG website reduces so much more?

**Comment by kevva** [comment]
By default we're only using OptiPNG to compress your images. Add https://github.com/imagemin/imagemin-pngquant for lossy compression.
