### ISSUE TITLE
Cannot Install

### ISSUE THREAD

**Issue by OwenMelbz** [gruntjs/grunt-contrib-imagemin#300]
I'm currently having issues installing this with the command

`npm install grunt-contrib-imagemin --save-dev`

my package.json looks like

```
{
  "name": "fatfriday",
  "version": "0.1.0",
  "description": "selesti fat friday internal project",
  "main": "Gruntfile.js",
  "scripts": {
    "test": "hi"
  },
  "repository": {
    "type": "git",
    "url": "git+https://owenmelbz@bitbucket.org/owenmelbz/fatfriday.git"
  },
  "author": "",
  "license": "ISC",
  "homepage": "https://bitbucket.org/owenmelbz/fatfriday#readme",
  "devDependencies": {
    "grunt": "^0.4.5",
    "grunt-autoprefixer": "^3.0.0",
    "grunt-browser-sync": "^1.9.2",
    "grunt-contrib-concat": "^0.5.1",
    "grunt-contrib-cssmin": "^0.12.2",
    "grunt-contrib-jshint": "^0.11.2",
    "grunt-contrib-less": "^1.0.1",
    "grunt-contrib-uglify": "^0.9.1",
    "grunt-contrib-watch": "^0.6.1",
    "grunt-newer": "^1.1.0",
    "grunt-notify": "^0.4.1",
    "matchdep": "^0.3.0"
  }
}
```

I've attached my `npm-debug.log` incase you can spot the issue [http://owenmelbourne.com/npm-debug.log](http://owenmelbourne.com/npm-debug.log)

Running `OSX Yasomite 10.10.3 (14D136)`

Help would be much appreciated! thank you

**Comment by sindresorhus** [comment]
> 48578 error If you need help, you may report this error at:
48578 error     <https://github.com/npm/npm/issues>

**Comment by OwenMelbz** [comment]
Considering this issue is directly related to your package, would it not be courteous to provide a certain level of support before passing the buck?

**Comment by kevva** [comment]
Why is it related to our package?

**Comment by sindresorhus** [comment]
@OwenMelbz You (and seemingly everyone on the internet) seem to not understand how npm works. Issues that occur during install is not ours and not something we can do anything about. We'd be happy to provide support for issues occurring during runtime, but issues with installing is with npm.

You don't complain to the restaurant if the taxi drive there was bad.
