### ISSUE TITLE
pngquant still installs

### ISSUE THREAD

**Issue by vladikoff** [gruntjs/grunt-contrib-imagemin#301]
@kevva I thought you removed it but during install I still get: 

```
> node lib/install.js

  ✔ pngquant pre-build test passed successfully
```

Also see travis log: https://travis-ci.org/gruntjs/grunt-contrib-imagemin/jobs/55399673#L110

Why is that?

**Comment by kevva** [comment]
Haven't published a new version of imagemin since we removed it. Will fix.

**Comment by sindresorhus** [comment]
Closing to clean up the issue tracker. If this is still an issue, open an issue on the relevant Imagemin plugin/binary repo instead.
