### ISSUE TITLE
Unsupported file layout

### ISSUE THREAD

**Issue by Guillawme** [gruntjs/grunt-contrib-imagemin#302]
I have this warning on jpg processing:
Running "imagemin:jpg" (imagemin) task
Warning: Error: Error: write EPIPE/usr/local/lib/libjpeg.so.11: unsupported file layout
 in file media/agenda/01_motown_revival.jpg Use --force to continue.

It works fine on png. I'm on FreeBSD, any idea?

**Comment by Guillawme** [comment]
When I install, some errors:

# npm install imagemin
npm WARN package.json radio-grunt@0.1.0 No description
npm WARN package.json radio-grunt@0.1.0 No repository field.
npm WARN package.json radio-grunt@0.1.0 No README data
 
> spawn-sync@1.0.6 postinstall /data/web/jazzradio/node_modules/imagemin/node_modules/imagemin-pngquant/node_modules/pngquant-bin/node_modules/bin-wrapper/node_modules/bin-check/node_modules/spawn-sync
> node postinstall

 
> spawn-sync@1.0.6 postinstall /data/web/jazzradio/node_modules/imagemin/node_modules/imagemin-optipng/node_modules/optipng-bin/node_modules/bin-wrapper/node_modules/bin-check/node_modules/spawn-sync
> node postinstall

 
> spawn-sync@1.0.6 postinstall /data/web/jazzradio/node_modules/imagemin/node_modules/imagemin-jpegtran/node_modules/jpegtran-bin/node_modules/bin-wrapper/node_modules/bin-check/node_modules/spawn-sync
> node postinstall

|
> spawn-sync@1.0.6 postinstall /data/web/jazzradio/node_modules/imagemin/node_modules/imagemin-gifsicle/node_modules/gifsicle/node_modules/bin-wrapper/node_modules/bin-check/node_modules/spawn-sync
> node postinstall

/
> jpegtran-bin@2.0.2 postinstall /data/web/jazzradio/node_modules/imagemin/node_modules/imagemin-jpegtran/node_modules/jpegtran-bin
> node lib/install.js

  ⚠ The `jpegtran` binary doesn't seem to work correctly
  ⚠ jpegtran pre-build test failed
  ℹ compiling from source
  ✖ Error: ./configure --disable-shared --prefix="/data/web/jazzradio/node_modules/imagemin/node_modules/imagemin-jpegtran/node_modules/jpegtran-bin/vendor" --bindir="/data/web/jazzradio/node_modules/imagemin/node_modules/imagemin-jpegtran/node_modules/jpegtran-bin/vendor" && make install
Command failed: configure: error: no nasm (Netwide Assembler) found

    at ChildProcess.exithandler (child_process.js:648:15)
    at ChildProcess.emit (events.js:98:17)
    at maybeClose (child_process.js:756:16)
    at Socket.<anonymous> (child_process.js:969:11)
    at Socket.emit (events.js:95:17)
    at Pipe.close (net.js:465:12)

> pngquant-bin@3.0.0 postinstall /data/web/jazzradio/node_modules/imagemin/node_modules/imagemin-pngquant/node_modules/pngquant-bin
> node lib/install.js

  ⚠ No binary found matching your system. It's probably not supported.
  ⚠ pngquant pre-build test failed
  ℹ compiling from source
  ✖ Error: pngquant failed to build, make sure that libpng-dev is installed
    at ChildProcess.exithandler (child_process.js:648:15)
    at ChildProcess.emit (events.js:98:17)
    at maybeClose (child_process.js:756:16)
    at Socket.<anonymous> (child_process.js:969:11)
    at Socket.emit (events.js:95:17)
    at Pipe.close (net.js:465:12)

> optipng-bin@2.0.4 postinstall /data/web/jazzradio/node_modules/imagemin/node_modules/imagemin-optipng/node_modules/optipng-bin
> node lib/install.js

  ⚠ /data/web/jazzradio/node_modules/imagemin/node_modules/imagemin-optipng/node_modules/optipng-bin/vendor/optipng 0.7.1 does not satisfy the version requirement of >=0.7.5
  ⚠ optipng pre-build test failed
  ℹ compiling from source
  ✖ Error: ./configure --with-system-zlib --prefix="/data/web/jazzradio/node_modules/imagemin/node_modules/imagemin-optipng/node_modules/optipng-bin/vendor" --bindir="/data/web/jazzradio/node_modules/imagemin/node_modules/imagemin-optipng/node_modules/optipng-bin/vendor" && make install
Command failed: usage: cp [-R [-H | -L | -P]] [-f | -i | -n] [-alpvx] source_file target_file
       cp [-R [-H | -L | -P]] [-f | -i | -n] [-alpvx] source_file ... target_directory

    at ChildProcess.exithandler (child_process.js:648:15)
    at ChildProcess.emit (events.js:98:17)
    at maybeClose (child_process.js:756:16)
    at Process.ChildProcess._handle.onexit (child_process.js:823:5)

> gifsicle@2.0.1 postinstall /data/web/jazzradio/node_modules/imagemin/node_modules/imagemin-gifsicle/node_modules/gifsicle
> node lib/install.js

  ⚠ Couldn't connect to https://raw.github.com/imagemin/gifsicle-bin/v2.0.1/vendor/freebsd/x64/gifsicle (404)
  ⚠ gifsicle pre-build test failed
  ℹ compiling from source
  ✔ gifsicle built successfully

imagemin@3.1.0 node_modules/imagemin
├── get-stdin@3.0.2
├── optional@0.1.3
├── stream-combiner@0.2.1 (duplexer@0.1.1, through@2.3.7)
├── vinyl@0.4.6 (clone-stats@0.0.1, clone@0.2.0)
├── meow@2.1.0 (object-assign@2.0.0, camelcase-keys@1.0.0, minimist@1.1.1, indent-string@1.2.1)
├── through2@0.6.5 (xtend@4.0.0, readable-stream@1.0.33)
├── concat-stream@1.4.8 (inherits@2.0.1, typedarray@0.0.6, readable-stream@1.1.13)
├── vinyl-fs@0.3.13 (graceful-fs@3.0.6, strip-bom@1.0.0, defaults@1.0.2, mkdirp@0.5.0, glob-stream@3.1.18, glob-watcher@0.0.6)
├── imagemin-svgo@4.1.2 (is-svg@1.1.1, svgo@0.5.1)
├── imagemin-jpegtran@4.1.0 (is-jpg@1.0.0, jpegtran-bin@2.0.2)
├── imagemin-pngquant@4.1.0 (is-png@1.0.0, pngquant-bin@3.0.0)
├── imagemin-optipng@4.2.0 (is-png@1.0.0, exec-buffer@2.0.1, optipng-bin@2.0.4)
└── imagemin-gifsicle@4.1.0 (is-gif@1.0.0, gifsicle@2.0.1)

**Comment by danaki** [comment]
Same issue

**Comment by HUNTERxp** [comment]
+1

**Comment by drook** [comment]
It's because npm brings a bogus jpegtran - 32-bit binary build for FreeBSD 9.0. Arch mismatch gives the error. FreeBSD has jpegtran in ports, so the solution is obvious.

**Comment by sindresorhus** [comment]
Closing to clean up the issue tracker. If this is still an issue, open an issue on the relevant Imagemin plugin/binary repo instead.
