### ISSUE TITLE
(imagemin) task Warning: undefined is not a function

### ISSUE THREAD

**Issue by juzhishang** [gruntjs/grunt-contrib-imagemin#304]
"devDependencies": {
    "grunt": "~0.4.5",
    "grunt-contrib-clean": "^0.6.0",
    "grunt-contrib-compass": "^1.0.3",
    "grunt-contrib-copy": "^0.8.0",
    "grunt-contrib-imagemin": "^0.9.4",
    "grunt-contrib-jshint": "^0.11.2",
    "grunt-contrib-nodeunit": "~0.4.1",
    "grunt-contrib-uglify": "~0.5.0",
    "grunt-contrib-watch": "^0.6.1",
    "grunt-include-replace": "^3.0.0"
  }

$ grunt imagemin
Running "imagemin:files" (imagemin) task
Warning: undefined is not a function Use --force to continue.

Aborted due to warnings.

**Comment by kevva** [comment]
Can you run it with the `--verbose` flag?

**Comment by juzhishang** [comment]
I ran "npm cache clean" and reinstalled it ,now it's ok~~
