### ISSUE TITLE
Fatal error: spawn cmd ENOENT

### ISSUE THREAD

**Issue by Zeldakkk** [gruntjs/grunt-contrib-imagemin#306]
Please help me fixing this:

Running "connect:livereload" (connect) task
Started connect web server on http://localhost:9000
spawn called
{ '0': 'cmd',
  '1': [ '/c', 'start', 'http://localhost:9000' ],
  '2': { stdio: 'ignore' } }
Fatal error: spawn cmd ENOENT

**Comment by sindresorhus** [comment]
Support questions are better asked on StackOverflow:
http://stackoverflow.com/questions/tagged/gruntjs
Paste in the link to the question here so others can follow ;)
