### ISSUE TITLE
Plugin is optimazing only 5%

### ISSUE THREAD

**Issue by dsoldera** [gruntjs/grunt-contrib-imagemin#309]
Hi there,

I'm trying to use this plugin, but the percent of optimazing/minify is only 5% the size of the image, even on Level 7.

Is there any other reports about it? 

Regards,

Danielle

**Comment by sindresorhus** [comment]
The amount it's able to optimize really depends on where the image was created. Photoshop is very wasteful and will optimize nicely, while other PNGs are already pretty minimal. YMMV. This is however not a bug though. You might want to try using additional plugins for even better optimizations.

**Comment by dsoldera** [comment]
Hi,

The images are all from Photoshop. Which plugin do you recommend to use
associated with imagemin?


Danielle Soldera
