### ISSUE TITLE
Jpegtran and Optipng will not compile Heroku

### ISSUE THREAD

**Issue by paulthegeek** [gruntjs/grunt-contrib-imagemin#311]
When I try to deploy to Heroku two of the image packages fail to compile Jpegtran and Optipng. Here are the logs from the Heroku server:

Node Version: 0.12.7
NPM Version: 2.11.3
##### Gifsicle will compile from source properly

`gifsicle@2.0.1 postinstall /tmp/build_dfd196e41523403d1848fee0f4104353/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/imagemin-gifsicle/node_modules/gifsicle
node lib/install.js`
  `⚠ The `gifsicle` binary doesn't seem to work correctly`
  `⚠ gifsicle pre-build test failed`
  `ℹ compiling from source`
  `✔ gifsicle built successfully`

`spawn-sync@1.0.11 postinstall /tmp/build_dfd196e41523403d1848fee0f4104353/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/imagemin-gifsicle/node_modules/gifsicle/node_modules/bin-wrapper/node_modules/bin-check/node_modules/spawn-sync
node postinstall`
##### Jpegtran does not compile from source properly

`jpegtran-bin@2.0.2 postinstall /tmp/build_dfd196e41523403d1848fee0f4104353/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/imagemin-jpegtran/node_modules/jpegtran-bin
node lib/install.js`

  `⚠ The `jpegtran` binary doesn't seem to work correctly`
  `⚠ jpegtran pre-build test failed`
  `ℹ compiling from source`
  `✖ Error: ./configure --disable-shared --prefix="/tmp/build_dfd196e41523403d1848fee0f4104353/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/imagemin-jpegtran/node_modules/jpegtran-bin/vendor" --bindir="/tmp/build_dfd196e41523403d1848fee0f4104353/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/imagemin-jpegtran/node_modules/jpegtran-bin/vendor" && make install
Command failed: /bin/sh -c ./configure --disable-shared --prefix="/tmp/build_dfd196e41523403d1848fee0f4104353/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/imagemin-jpegtran/node_modules/jpegtran-bin/vendor" --bindir="/tmp/build_dfd196e41523403d1848fee0f4104353/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/imagemin-jpegtran/node_modules/jpegtran-bin/vendor"`
`/bin/sh: 1: ./configure: not found`
    `at ChildProcess.exithandler (child_process.js:751:12)`
    `at ChildProcess.emit (events.js:110:17)`
    `at maybeClose (child_process.js:1015:16)`
    `at Process.ChildProcess._handle.onexit (child_process.js:1087:5)`

`spawn-sync@1.0.11 postinstall /tmp/build_dfd196e41523403d1848fee0f4104353/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/imagemin-jpegtran/node_modules/jpegtran-bin/node_modules/bin-wrapper/node_modules/bin-check/node_modules/spawn-sync
node postinstall`
##### Optipng does not compile from source properly

`optipng-bin@2.0.4 postinstall /tmp/build_dfd196e41523403d1848fee0f4104353/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/imagemin-optipng/node_modules/optipng-bin
node lib/install.js`
  `⚠ The `optipng` binary doesn't seem to work correctly`
  `⚠ optipng pre-build test failed`
  `ℹ compiling from source`
  `✖ Error: ./configure --with-system-zlib --prefix="/tmp/build_dfd196e41523403d1848fee0f4104353/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/imagemin-optipng/node_modules/optipng-bin/vendor" --bindir="/tmp/build_dfd196e41523403d1848fee0f4104353/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/imagemin-optipng/node_modules/optipng-bin/vendor" && make install`
`Command failed: /bin/sh -c ./configure --with-system-zlib --prefix="/tmp/build_dfd196e41523403d1848fee0f4104353/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/imagemin-optipng/node_modules/optipng-bin/vendor" --bindir="/tmp/build_dfd196e41523403d1848fee0f4104353/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/imagemin-optipng/node_modules/optipng-bin/vendor"`
`/bin/sh: 1: ./configure: not found`
    `at ChildProcess.exithandler (child_process.js:751:12)`
    `at ChildProcess.emit (events.js:110:17)`
    `at maybeClose (child_process.js:1015:16)`
    `at Socket.<anonymous> (child_process.js:1183:11)`
    `at Socket.emit (events.js:107:17)`
    `at Pipe.close (net.js:485:12)`

**Comment by mashbourne** [comment]
Seeing similar behavior on RHEL 6.6
`optipng-bin@1.0.1 postinstall /node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/imagemin-optipng/node_modules/optipng-bin
21:00:40 > node lib/install.js`
`Error: Command failed: /bin/sh: ./configure: No such file or directory`

`Error: Command failed: /node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/imagemin-optipng/node_modules/optipng-bin/vendor/optipng: /lib64/libc.so.6: version 'GLIBC_2.14' not found (required by /node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/imagemin-optipng/node_modules/optipng-bin/vendor/optipng`

**Comment by Lordnibbler** [comment]
same issue here

**Comment by santiagovazquez** [comment]
same issue here :(

**Comment by chfw** [comment]
same issue here on centos 7.2

**Comment by chfw** [comment]
I noticed that if grunt-contrib-imagemin v0.3.0 is used, all build will pass despite the warnings.

    > pngquant-bin@0.1.7 postinstall /var/lib/jenkins/workspace/checkout/gui/node_modules/pngquant-bin
    > node index.js

    ✗ unable to get local issuer certificate

    > optipng-bin@0.3.11 postinstall /var/lib/jenkins/workspace/checkout/gui/node_modules/optipng-bin
    > node index.js


    > jpegtran-bin@0.2.8 postinstall /var/lib/jenkins/workspace/checkout/gui/node_modules/jpegtran-bin
    > node index.js


    > gifsicle@0.1.7 postinstall /var/lib/jenkins/workspace/checkout/gui/node_modules/gifsicle
    > node index.js

    ⚠ pre-build test failed, compiling from source...
    ✖ { [Error: Command failed: /bin/sh -c ./configure --disable-gifview --disable-gifdiff --prefix="/var/lib/jenkins/workspace/checkout/gui/node_modules/gifsicle/vendor" --bindir="/var/lib/jenkins/workspace/checkout/gui/node_modules/gifsicle/vendor" && make install
    /bin/sh: ./configure: No such file or directory
    ]
      killed: false,
      code: 127,
      signal: null,
      cmd: '/bin/sh -c ./configure --disable-gifview --disable-gifdiff --prefix="/var/lib/jenkins/workspace/checkout/gui/node_modules/gifsicle/vendor" --bindir="/var/lib/jenkins/workspace/checkout/gui/node_modules/gifsicle/vendor" && make install' }
    ✔ gifsicle built successfully!

**Comment by szechyjs** [comment]
same issue on centos 5

**Comment by sindresorhus** [comment]
Closing to clean up the issue tracker. If this is still an issue, open an issue on the relevant Imagemin plugin/binary repo instead.
