### ISSUE TITLE
grunt imagemin running but not minifying 

### ISSUE THREAD

**Issue by douglasdeodato** [gruntjs/grunt-contrib-imagemin#317]
hey guys after i run the code on my terminal:

$ grunt imagemin
Running "imagemin:dist" (imagemin) task
Minified 0 images (saved 0 B)

Done, without errors.

I am not understand, i tried loads deferents images and still not compressing.

imagemin part on my grunt:

//Image min ===============================

```
            var imagemin;
            config.imagemin = imagemin = {};
                imagemin.dist = {
                     options: {
                            optimizationLevel: 5,
                            progressive: true,
                          },
                    dynamic: {
                        files: [{
                            expand: true,
                            cwd: 'assets/images',
                            src: ['**/*.{png,jpg,gif}'],
                            dest: 'public/images'
                        }]
                    }

                };  
```

**Comment by larstid** [comment]
Hi,
i have the same problem. The Task is run without a problem, but there is no output. I got the newest node version v0.12.7. I'm using Grunt to run the task.

After the task is completed i get this message. There are several images in different formats but no Output at all.

Running "imagemin:dynamic" (imagemin) task
Minified 0 images (saved 0 B)

    imagemin: {                          
    dynamic: {                          
      options: {                       
        optimizationLevel: 3
      },
      dist:{
        src: 'img/',
        dest: 'dist/'
      }
  }

Hope you guys can fix it.

**Comment by BryanBarrera** [comment]
How are you registering your task? @larstid @douglasdeodato

**Comment by douglasdeodato** [comment]
grunt.registerTask('default',['dev']);
grunt.registerTask('dev',['imagemin']);

that is what i get after run:

$ grunt imagemin
Running "imagemin:dist" (imagemin) task
Minified 0 images (saved 0 B)

Done, without errors.

**Comment by BryanBarrera** [comment]
Try to use my gruntfile as a reference here - `https://github.com/gruntjs/grunt-contrib-imagemin/issues/322`

I ran into the same issue but slightly different than yours. It looks like the file paths may be wrong on your end, that is why `imagemin`  isn't compressing anything.

**Comment by douglasdeodato** [comment]
hey man, sorry but i am not getting error, just the images don't get minimized, if I do one by one works, but getting full repository no :(, 

grunt imagemin always run and return that for me:

Running "imagemin:dist" (imagemin) task
Minified 0 images (saved 0 B)

Done, without errors.

**Comment by douglasdeodato** [comment]
solved: i removed dynamic: { } and now is running, thanks all.

var imagemin;
            config.imagemin = imagemin = {};
                imagemin.dist = {
                     options: {
                            optimizationLevel: 5,
                            progressive: true,
                          },
                   
                        files: [{
                            expand: true,
                            cwd: 'assets/images',
                            src: ['**/*.{png,jpg,gif}'],
                            dest: 'public/images'
                        }]
                

                };

**Comment by larstid** [comment]
Thanks guys, for these solutions but they're not working for me.

Here's what my gruntfile looks like:

module.exports = function(grunt) {

  // Project configuration.
  grunt.initConfig({
  imagemin: {                          // Task                          
    dynamic: {                         // Another target
      files: [{
        expand: true,                  // Enable dynamic expansion
        cwd: 'src/',                   // Src matches are relative to this path
        src: ['**/*.{png,jpg,gif}'],   // Actual patterns to match
        dest: 'dist/img/opt'                  // Destination path prefix
      }]
    },
    options: {                       // Target options
        optimizationLevel: 5
  }
}
  });

  // imagemin
  grunt.loadNpmTasks('grunt-contrib-imagemin');

  // Default task(s).
  grunt.registerTask('default', ['imagemin']);

};

I've tried imagemin on my mac and i got installation problems (optipng pre build test failed), so i tried to install it on my pc. The Installation on my pc was successful but like i said before imagemin is not compressing any Pictures. I get always the Message:
Running "imagemin:dynamic" (imagemin) task
Minified 0 images (saved 0B)
Done, without errors.

So neither on my mac nor on my pc can i use imagemin. I have the newest Version of node.js installed every other Grunt tasks are running perfectly fine.

**Comment by BryanBarrera** [comment]
what is the path to the folder your images are in? @larstid

**Comment by douglasdeodato** [comment]
src folder should exist., and remove dynamic {} see mine:

//Image min ===============================

            var imagemin;
            config.imagemin = imagemin = {};
                imagemin.dist = {
                     options: {
                            optimizationLevel: 5,
                            progressive: true,
                          },

                        files: [{
                            expand: true,
                            cwd: 'assets/images',  // that folder should exist with all images
                            src: ['**/*.{png,jpg,gif}'],
                            dest: 'public/images'   // where is going your min files
                        }]

                };

**Comment by MandyMadeThis** [comment]
ISSUE RESOLVED:

I ended up adding another plugin and my jpegs are now compressing! Since there are no options listed for the jpegtran plugin that comes bundled with Imagemin, I installed imagemin-jpegoptim. 

`module.exports = function(grunt) {

    var jpegOptim = require('imagemin-jpegoptim');

    grunt.initConfig({

        pkg: grunt.file.readJSON('package.json'),

        imagemin: {
            dynamic: {
                options: { 
                    full:true,
                    optimizationLevel: 5,
                    svgoPlugins: [
                        { removeViewBox: false },
                        { cleanupIDs: false }
                    ],
                    use: [jpegOptim({max:60})]
                },
              files: [{
                expand: true,
                cwd: 'assets-images/',
                src: ['**/*.{png,jpg,gif}'],
                dest: 'images/'  
              }]
            }
        },
   };`

**Comment by sindresorhus** [comment]
Closing to clean up the issue tracker. If this is still an issue, open an issue on the relevant Imagemin plugin/binary repo instead.
