### ISSUE TITLE
Error: spawn ENOENT

### ISSUE THREAD

**Issue by danielmedina** [gruntjs/grunt-contrib-imagemin#321]
I'm havin some troubles to build my application. When I execute imagemin task, it returns the following error:
```
Warning: Error: spawn /data/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/imagemin-gifsicle/node_modules/gifsicle/vendor/gifsicle ENOENT in file app/assets/images/loading.gif Use --force to continue.
```

here is my task:

``` javascript
imagemin: {
      dist: {
        files: [
          {
            expand: true,
            cwd: '<%= appConfig.app %>/assets/images',
            src: '*.{png,jpg,jpeg,gif,svg}',
            dest: '<%= appConfig.dist %>/images'
          }
        ]
      }
    }
```

Any clues?

**Comment by sindresorhus** [comment]
Try reinstalling and look at the CLI output. Looks like the install failed somehow.

**Comment by danielmedina** [comment]
my problem is that my application is builded using bamboo by a docker container. I have other applications using the same container an using grunt-contrib-imagemin. Works fine.

So, I don't have access to this container. I tried to remove grunt-contrib-imagemin from package.json expecting that the process remove it. It runs npm prune before anything. After that, I inserted grunt-contrib-imagemin again in package.json and the error persist.

Reading the log, I discovered an error that could be associated with my problem:

´´´
npm WARN cannot run in wd gifsicle@3.0.1 node lib/install.js (wd=/data/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/imagemin-gifsicle/node_modules/gifsicle)
´´´

I really don't know how to start to resolve this problem...

**Comment by dtolj** [comment]
Same problem here on Linux when issues ```$ grunt```
I have ```"imagemin-gifsicle": "^4.2.0"``` and ```"grunt-contrib-imagemin": "^0.9.4"```
```
 Warning: Running "imagemin:dist" (imagemin) task
    Warning: Error: spawn /root/mytodo/node_modules/imagemin/node_modules/imagemin-optipng/node_modules/optipng-bin/vendor/optipng ENOENT in file app/images/yeoman.png Use --force to continue.
Aborted due to warnings.

**Comment by MZAWeb** [comment]
+1. Exactly same issue as @dtolj

**Comment by pagoenka** [comment]
I am too getting same issue 

    Warning: Running "imagemin:dist" (imagemin) task
    Warning: Error: spawn /Volumes/Data/LS/source/UI/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/imagemin-gifsicle/node_modules/gifsicle/vendor/gifsicle ENOENT in file

Anyone found any solution??

**Comment by pagoenka** [comment]
When I ran my grunt build with sudo it worked!!

**Comment by pcssi** [comment]
+1. Same issue [as](https://github.com/gruntjs/grunt-contrib-imagemin/issues/321#issuecomment-142090656) @dtolj [and](https://github.com/gruntjs/grunt-contrib-imagemin/issues/321#issuecomment-142444813) @MZAWeb.

**Comment by GilmarLira** [comment]
Ok, I was having this very same issue, was super frustrated, but after hours of research I finally figured it out. 

As @pagoenka suggested in his comment, a npm permission issue prevents some grunt-contrib-imagemin dependencies to install correctly. Here's what I did to fix it:

1. Fix npm permissions by following their own instructions: 
https://docs.npmjs.com/getting-started/fixing-npm-permissions

2. Delete project's node_modules/ folder

3. Restart

4. Reinstall node modules by running npm install at the projects folder.


Hope this helps.

Cheers!

**Comment by aruis** [comment]
try:
npm uninstall grunt-contrib-imagemin
npm install grunt-contrib-imagemin

**Comment by dpalic** [comment]
@aruis 
your suggestion with uninstall and install did the trick for me. Big thx, saved my day!

**Comment by JnMik** [comment]
Well I tried what GilmarLira said, but to no avail.

I now have this error..

Warning: Error: spawn some-project-root-path/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/imagemin-gifsicle/node_modules/gifsicle/vendor/gifsicle ENOENT in file some-project-root-path/dist/default-skin/preloader.gif Use --force to continue.

**Comment by JnMik** [comment]
Ok.. now that the PR is merge, i've tried with grunt-contrib-imagemin: 1.0.0 and I still have the issue, BUT I found a workaround.

After my npm install, if I overwrite versions of these 3 packages I have no more problems
npm install jpegtran-bin@3.0.4
npm install gifsicle@3.0.1
npm install optipng-bin@3.0.1

Each one fix the issues for the matching image type (jpeg, gif, png).

My guess is : 
grunt-contrib-imagemin requires  "imagemin": "^4.0.0"

imagemin 4.0.0 requires : 
"imagemin-gifsicle": "^4.0.0",
"imagemin-jpegtran": "^4.0.0",
 "imagemin-optipng": "^4.0.0",

and those latests versions of package are not working properly.

**Comment by kidleaf1** [comment]
@aruis It works me,thx

**Comment by ikb42** [comment]
@aruis works!

**Comment by montaro** [comment]
@aruis Worked!

**Comment by darkmavis1980** [comment]
Removing the node_modules folder and reinstalling everything did the trick for me as well

**Comment by lenybernard** [comment]
Hello,

I finally figured out why I was experiencing this issue :

- I have a 64bytes architecture system
- It does works properly when I runin local
- I've created a docker container (which is 32bytes arch)
- the same command does not work inside the container

As @darkmavis1980 said, the solution is to add `/node_modules` to the `.dockerignore` file or to remove the directory before each new deployment.

**Comment by g1eb** [comment]
@aruis +1

**Comment by geetwo** [comment]
@aruis +1

**Comment by doug-orchard** [comment]
@aruis +1

**Comment by alinturbut** [comment]
@GilmarLira your sollution worked for me. 

Guys, please also check you have full rights on the folder you are running npm install.

**Comment by dvodonnell** [comment]
Note that I had spawn ENOENT issues but only sporadically. Issue turned out to be no swap space on my machine: http://stackoverflow.com/a/32444643/389765

**Comment by lricoy** [comment]
The simple and clean fix from @aruis worked for me. +1

**Comment by gitoneman** [comment]
@aruis thx!

**Comment by darkmavis1980** [comment]
I had the same issue on another server, and this time I had to uninstall and reinstall the package, removing the entire `node_modules` folder didn't the trick this time, which it doesn't make any sense to me.

**Comment by so77id** [comment]
@aruis +1

**Comment by vladyn** [comment]
I tried uninstall / install - doesn't worked for me 

I'm getting 
`Error: spawn /..  jpegqran ENOENT in` in file .../

**Comment by wesley100002001** [comment]
@aruis 
Thx!!! You saved my day!!!

**Comment by oleole90** [comment]
@aruis, had to uninstall/install couple of packages but your solution worked fine. 👍

**Comment by zhaomengru2015** [comment]
@aruis: works for me

**Comment by basileos** [comment]
Reproduces on "node":"4.4.5","npm":"2.15.5" - ```
Warning: Running "imagemin:dist" (imagemin) task
    Warning: Error: spawn /Development/guts-server/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/imagemin-gifsicle/node_modules/gifsicle/vendor/gifsicle ENOENT in file app/public/images/ajax-loader.gif Use --force to continue.
```
from my config - 
```
         imagemin: {
             dist: {
                 files: [{
                     expand: true,
                     cwd: '<%= yeoman.app %>/images',
                     src: '{,*/}*.{png,jpg,jpeg,gif}',
                     dest: '<%= yeoman.dist %>/images'
                 }]
             }
         },
```

**Comment by muthuspark** [comment]
@aruis +1

**Comment by onewayxp** [comment]
in my case，
try below, works for me.
node node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/imagemin-gifsicle/node_modules/gifsicle/lib/install.js

**Comment by ann--b** [comment]
@GilmarLira +1

The npm permissions were my problem.  I chose option 2 from the [npm permission instructions](https://docs.npmjs.com/getting-started/fixing-npm-permissions) you provided.  Changed the npm default directory from /usr/local to ~/.npm-global.  I didn't want to change /usr/local/bin or /usr/local/share permissions.  Then I followed the rest of your instructions and it worked!  Thank you.

**Comment by wuyuchang** [comment]
@aruis  it's work after I reinstall "grunt-contrib-imagemin".

**Comment by nyn05** [comment]
@aruis +1

**Comment by numediaweb** [comment]
Is there any permanent fix for this issue?

**Comment by jorrit** [comment]
No. I have mailed the maintainers to inform if they are interested in a patch but I got no response. This project seems dead.

**Comment by nyn05** [comment]
There is an important tip for persons who are in some countries like Iran, they cant install imagemin completely because the server refuse to connect them, they have to connect via a VPN connection to completely install imagemin

**Comment by mousavi86** [comment]
@aruis
Save 2 hours at least for me.

**Comment by derekrprice** [comment]
@arius's suggestion wasn't quite enough - I had to clean the cache too.
`npm cache clean && npm uninstall grunt-contrib-imagemin && npm install grunt-contrib-imagemin`

**Comment by junfangfan** [comment]
error: spawn /projects/website/haifang/node_modules/optipng-bin/vendor/optipng ENOENT
    at exports._errnoException (util.js:1050:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:367:16)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)...
Who can resolve this problems?thank you !!!

**Comment by josefsabl** [comment]
Removing /node-modules are running npm install again did the trick. What a mess :-(

**Comment by ndinhphi** [comment]
> Ok, I was having this very same issue, was super frustrated, but after hours of research I finally figured it out.
> 
> As @pagoenka suggested in his comment, a npm permission issue prevents some grunt-contrib-imagemin dependencies to install correctly. Here's what I did to fix it:
> 
> 1. Fix npm permissions by following their own instructions:
>    https://docs.npmjs.com/getting-started/fixing-npm-permissions
> 2. Delete project's node_modules/ folder
> 3. Restart
> 4. Reinstall node modules by running npm install at the projects folder.
> 
> Hope this helps.
> 
> Cheers!

I have to login and give you a thumbsup
Thank you so much!

**Comment by WebMago** [comment]
> in my case，
> try below, works for me.
> node node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/imagemin-gifsicle/node_modules/gifsicle/lib/install.js

This solve my build on Docker Container on a oldest project, thanks a lot

**Comment by thanatos11** [comment]
> try:
> npm uninstall grunt-contrib-imagemin
> npm install grunt-contrib-imagemin

actually worked for me. Thank you so much
