### ISSUE TITLE
Error: write EPIPE

### ISSUE THREAD

**Issue by velnikolic** [gruntjs/grunt-contrib-imagemin#323]
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: write EPIPE
    at Object.exports._errnoException (util.js:874:11)
    at exports._exceptionWithHostPort (util.js:897:20)
    at WriteWrap.afterWrite (net.js:763:14)
Velibors-MacBook-Pro:gulp3 vel$ 

I am getting this error when compiling with Gulp. When I remove imagemin from the gulpfile.js everything works fine. I am running OSX Capitan

**Comment by paulcpederson** [comment]
@velnikolic this is the repository for the grunt plugin, so probably not where you meant to open this issue?
