### ISSUE TITLE
enhancement/question: verbose output

### ISSUE THREAD

**Issue by AlphaHasi** [gruntjs/grunt-contrib-imagemin#326]
As far as I understand there are several stages of grunt verbose output: 0 (nothing) - 3 (everything).

I am working on a project with several hundred images (inside folder src are the originals and in folder files are the optimized images) . I also use newer, so that I am not every time update all the images.

If I use "verbose: 0", I get only the information (e.g.) "2 images optimized". If I use "verbose: 1" (or 2 or 3) I get listet all (!) images (path original -> path optimized) and after this list the actual handled images (like: image 1 filename, saved 200KB, image 2 filename saved ...).

I think it would be a good enhancement to use the verbose states and give the complete data (list of all images and handled images) only in verbose stage 3, but for example in stage 1 only the actual handled images (so in my example above only 2 lines (plus summary) instead of some hundreds).

Thx!

**Comment by kevva** [comment]
Grunt does not have different log levels AFAIK, only `verbose` or not.
