### ISSUE TITLE
Error while installing with Node 4.2.2

### ISSUE THREAD

**Issue by lvarayut** [gruntjs/grunt-contrib-imagemin#327]
I got some errors while trying to install this plugin with Node 4.x as mentioned in [Error while installing 3.0.0-rc8 with Node 4.2.2](https://github.com/DaftMonk/generator-angular-fullstack/issues/1412#issuecomment-154512525).

I'm using the latest version of this plugin; 0.9.4. Any help would be appreciated.

**Comment by vladikoff** [comment]
Please try with 1.0.0
