### ISSUE TITLE
imagemin:dist Error

### ISSUE THREAD

**Issue by kuldeepkeshwar** [gruntjs/grunt-contrib-imagemin#332]
Hi,
I'm getting the below error after taking latest imagemin updates.

[4mRunning "concurrent:dist" (concurrent) task[24m
    
    [4mRunning "svgmin:dist" (svgmin) task[24m
    Total saved: 0 B
    
    [32mDone, without errors.[39m
    
    
    Execution Time (2015-11-14 09:31:48 UTC)
    loading tasks         288ms  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 71%
    loading grunt-svgmin   62ms  ▇▇▇▇▇▇▇ 15%
    svgmin:dist            53ms  ▇▇▇▇▇▇ 13%
    Total 404ms
        [33mWarning: [4mRunning "imagemin:dist" (imagemin) task[24m
    [31mFatal error: Cannot read property 'contents' of undefined[39m
    
    
    Execution Time (2015-11-14 09:31:48 UTC)
    loading tasks                   373ms  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 58%
    loading grunt-contrib-imagemin  180ms  ▇▇▇▇▇▇▇▇▇ 28%
    imagemin:dist                    91ms  ▇▇▇▇▇ 14%
    Total 645ms Use --force to continue.[39m
        
        [31mAborted due to warnings.[39m
    

Execution Time (2015-11-14 09:31:46 UTC)
loading tasks                 263ms  ▇▇▇▇ 10%
loading grunt-contrib-jshint   88ms  ▇▇ 3%
jshint:all                    580ms  ▇▇▇▇▇▇▇▇ 22%
jshint:test                   257ms  ▇▇▇▇ 10%
jsinspect:inspect             122ms  ▇▇ 5%
wiredep:app                   110ms  ▇▇ 4%
loading grunt-usemin           29ms  ▇ 1%
concurrent:dist                1.1s  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 41%
Total 2.6s

**Comment by axetroy** [comment]
i had meet this error
but i don't know how to fix this.....

**Comment by Couto** [comment]
I can confirm that his happens with node v5.1.0. 
I've regressed to node v0.12.7, reinstalled the packages and the error is gone.

**Comment by kuldeepkeshwar** [comment]
after updating to the latest(v1.0.0) ,it is gone, so closing this issue
