### ISSUE TITLE
Cannot read property 'contents' of undefined

### ISSUE THREAD

**Issue by axetroy** [gruntjs/grunt-contrib-imagemin#333]
$ grunt build
Running "clean:dist" (clean) task
>> 4 paths cleaned.

Running "wiredep:app" (wiredep) task

Running "wiredep:test" (wiredep) task

Running "wiredep:sass" (wiredep) task

Running "useminPrepare:html" (useminPrepare) task
Configuration changed for concat, uglify, cssmin

Running "concurrent:dist" (concurrent) task
    
    Running "svgmin:dist" (svgmin) task
    Total saved: 0 B
    
    Done, without errors.
    
    
    Execution Time (2015-11-17 01:46:50 UTC)
    loading tasks          6ms  ▇▇▇ 6%
    loading grunt-svgmin  52ms  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 55%
    svgmin:dist           36ms  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 38%
    Total 95ms
        Warning: Running "imagemin:dist" (imagemin) task
    Fatal error: Cannot read property 'contents' of undefined
    
    
    Execution Time (2015-11-17 01:46:50 UTC)
    loading tasks                    10ms  ▇ 3%
    loading grunt-contrib-imagemin  189ms  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 63%
    imagemin:dist                   103ms  ▇▇▇▇▇▇▇▇▇▇▇ 34%
    Total 302ms Use --force to continue.
        
        Aborted due to warnings.
    

Execution Time (2015-11-17 01:46:50 UTC)
clean:dist              9ms  ▇▇ 1%
wiredep:app            94ms  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 11%
wiredep:test            9ms  ▇▇ 1%
wiredep:sass           12ms  ▇▇ 1%
loading grunt-usemin   39ms  ▇▇▇▇▇▇ 5%
useminPrepare:html     17ms  ▇▇▇ 2%
concurrent:dist       662ms  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 77%
Total 857ms

**Comment by axetroy** [comment]
Warning: Running "imagemin:dist" (imagemin) task
Fatal error: Cannot read property 'contents' of undefined

how to do this?
can somebody help,plz!

**Comment by lvarayut** [comment]
Duplicated with #330

**Comment by jorrit** [comment]
And solved in 1.0.0.

**Comment by chenlexing** [comment]
changed the grunt-contrib-imagemin version to 1.0.0 and imagemin version to 4.0.0, as below prcture
![24abaf06-0578-4696-badf-d902450cfaff](https://cloud.githubusercontent.com/assets/7897528/11360023/02077fb4-92bc-11e5-849f-7edde1d1dd33.png)

**Comment by michaelaharvey** [comment]
thank you! ^^

**Comment by alejandroiglesias** [comment]
Same here with `grunt-contrib-config` version `1.0.0` and `imagemin` version `4.0.0`.

**Comment by alejandroiglesias** [comment]
Fixed by running `npm cache clean && npm install grunt-contrib-imagemin` as suggested in #208. This should be closed.

**Comment by ronyvieira** [comment]
@alejandroiglesias Thank you!

**Comment by warpdesign** [comment]
I am still getting this error, with grunt-contrib-imagemin 1.0.0 & imagemin 4.0.0

Running `npm cache clean && npm install grunt-contrib-imagemin` didn't help.

**Comment by jorrit** [comment]
I think it is best to concentrate the discussion in #330.

**Comment by firsyura** [comment]
@alejandroiglesias :+1: It works for me

**Comment by HerneWyldwood** [comment]
npm cache clean && npm install grunt-contrib-imagemin did not work for me
