### ISSUE TITLE
Getting occasional corrupted images on v1.0.0

### ISSUE THREAD

**Issue by haveric** [gruntjs/grunt-contrib-imagemin#335]
Recently updated to v1.0.0 due to the "Cannot read property 'contents' of undefined" issue. Have noticed two times now that a couple images have gotten corrupted using the following:
```
var config = {
    img: 'webapp/img'
};

grunt.initConfig({
    imagemin: {
        options: {
            optimizationLevel: 7
        },
        dynamic: {
            files: [{
                expand: true,
                cwd: '<%= config.img %>',
                src: ['**/*.{png,jpg,gif}'],
                dest: '<%= config.img %>'
            }]
        }
    }
});
```

Unfortunately, it has been inconsistent in doing this. Putting the originals back in and rerunning has worked both times. If it helps, the two images that got corrupted this time were both jpg's (but there were others that did not get corrupted).

I'm going to see if I can recreate this tonight. Let me know if there's any other information I can provide.

**Comment by sindresorhus** [comment]
Closing for lack of followup.
