### ISSUE TITLE
grunt imagemin doesn't compress images on newly created subfolders

### ISSUE THREAD

**Issue by vlrprbttst** [gruntjs/grunt-contrib-imagemin#337]
hi
i use grunt imagemin with grunt newer and grunt watch and it works great, except it doesn't trigger when i create a new subfolder and save files in there. here's my gruntfile

**the watch task**
 ```
watch: {
      graphical_assets: {
        files: ['source/images/**/*.{png,jpg,gif,jpeg}'],
        tasks: ['newer:imagemin'], 
      } 
    }
```

**imagemin task**
```
    imagemin : {
      dynamic : {
        files : [{
          expand : true, // Enable dynamic expansion
          cwd : 'source/images/', // source images (not compressed)
          src : ['**/*.png','**/*.gif','**/*.jpg','**/*.jpeg'], // Actual patterns to match
          dest : 'package/assets/images/' // Destination of compressed files
        }]
      }
    },
```

**the end of the gruntfile**
```
  grunt.loadNpmTasks('grunt-newer');
  grunt.loadNpmTasks('grunt-contrib-imagemin');
  grunt.registerTask('default', ['watch']);
```

as I said everything works fine *except* on newly created subfolders, unless i expressly type `grunt imagemin`. when i manually do it, from that moment on, grunt imagemin will recognize that new subfolder as something to watch and compress.

any help? thanks! :)

**Comment by sindresorhus** [comment]
Support questions are better asked on StackOverflow:
http://stackoverflow.com/questions/tagged/gruntjs
Paste in the link to the question here so others can follow ;)

-

This is related to the watch or newer task, not this one.
