### ISSUE TITLE
Unable to use Compact Format for src-dest

### ISSUE THREAD

**Issue by tfrommen** [gruntjs/grunt-contrib-imagemin#340]
Either I'm doing something very wrong, or `grunt-contrib-imagemin` isn't capable of understanding src-dest in the [Compact Format](http://gruntjs.com/configuring-tasks#compact-format).

Running `$ grunt` with the following `Gruntfile.js` works perfectly fine:

``` js
module.exports = function( grunt ) {

    require( 'load-grunt-tasks' )( grunt );

    grunt.initConfig( {
        imagemin: {
            images: {
                expand: true,
                cwd: 'resources/images/',
                src: [ '**/*.{gif,jpeg,jpg,png}' ],
                dest: 'src/assets/images/'
            }
        }
    } );

    grunt.registerTask( 'default', 'imagemin' );
};
```

Instead of the `expand`ed format, I would rather define `src` and `dest` in the Compact Format, for a number of reasons (e.g., I don't use `ext` or `extDot`, or need `cwd`, and `grunt-newer` doesn't function properly with the `expand`ed format). This would be the following:

``` js
module.exports = function( grunt ) {

    require( 'load-grunt-tasks' )( grunt );

    grunt.initConfig( {
        imagemin: {
            images: {
                src: [ 'resources/images/**/*.{gif,jpeg,jpg,png}' ],
                dest: 'src/assets/images/'
            }
        }
    } );

    grunt.registerTask( 'default', 'imagemin' );
};
```

When running `$ grunt` with the above config, there will be a single **file** `src/assets/images` created (which basically is the first source image). So, why is that?

Yes, I did see that the examples only listed static and `expand`ed format. But I couldn't find anything on compact format not working properly. Why shouldn't it work anyway?

Am I doing something wrong? Using `grunt-lineending` with the exact same config (for `.css` and `.js` files, of course) works perfectly fine.

**Comment by sindresorhus** [comment]
Yes, it doesn't support the compact format. Not interested in supporting it either at this point as Grunt is basically dead.
