### ISSUE TITLE
Does not working with grunt-newer

### ISSUE THREAD

**Issue by rmevans1** [gruntjs/grunt-contrib-imagemin#342]
I am using this with grunt-newer.

When running the command newer:imagemin it resizes the image the first time as expected. However, on the second run through it still minifies the original images.

**Comment by sindresorhus** [comment]
`grunt-newer` does not work with this plugin.

https://github.com/tschaub/grunt-newer/issues/new

**Comment by rmevans1** [comment]
Then you may want to remove this from the Readme We recommend using grunt-newer to only process changed files as minifying images can be quite slow.
