### ISSUE TITLE
Minification fails

### ISSUE THREAD

**Issue by Everlost81** [gruntjs/grunt-contrib-imagemin#344]
Getting this when our build runs.

Running "imagemin:dist" (imagemin) task
Fatal error: Cannot read property 'contents' of undefined 

Nothing in the project has been changed for weeks. 

I can see that the dependencies of imagemin 4.0.0 has changed to:
imagemin@4.0.0 (optional@0.1.3, stream-combiner2@1.1.1, concat-stream@1.5.1, buffer-to-vinyl@1.1.0, readable-stream@2.0.5, vinyl-fs@2.3.0, imagemin-optipng@4.3.0, imagemin-gifsicle@4.2.0, imagemin-svgo@4.2.0, imagemin-jpegtran@4.3.2)

from:
imagemin@4.0.0 (optional@0.1.3, stream-combiner2@1.1.1, concat-stream@1.5.1, buffer-to-vinyl@1.1.0, readable-stream@2.0.5, vinyl-fs@2.2.1, imagemin-jpegtran@4.3.2, imagemin-svgo@4.2.0, imagemin-optipng@4.3.0, imagemin-gifsicle@4.2.0)

without the imagemin changing version.

This also seems like it's a breaking build?

**Comment by derdaani** [comment]
+1 same issue here.

**Comment by awudarowicz** [comment]
+1 same to me :(

**Comment by asmogan** [comment]
+1 same here

**Comment by squirrelito** [comment]
Just hit that ... added "vinyl-fs": "2.2.1" as dependency in order to get the build up and running but I see this happening for 2nd time.

**Comment by samgooch** [comment]
+1 same here

**Comment by derdaani** [comment]
@squirrelito thx for proposing your quick fix. At least we're able to release today...

**Comment by Everlost81** [comment]
@squirrelito Aye, same issue as on the 10th of November last year. It's a shame. Changing vinyl-fs back to the old version should do the trick yes.

**Comment by rhedman** [comment]
+1

**Comment by peruzzo** [comment]
+1

**Comment by jivinivan** [comment]
I'm receiving the following error when forcing "vinyl-fs": "2.2.1".

```
module.js:340
    throw err;
          ^
Error: Cannot find module 'readable-stream/passthrough'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/ubuntu/ambassador-client/node_modules/vinyl-fs/node_modules/merge-stream/index.js:3:19)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
```

**Comment by Everlost81** [comment]
@jivinivan Worked for me. Are you using grunt-contrib-imagemin 1.0.0?

**Comment by rhedman** [comment]
Works for me when forcing vinyl-fs to 2.2.1 in my local environment. Unfortunately that won't help when deploying to dev since the build reinstalls all node modules and thus reinstalls 2.3.0 =/

**Comment by Everlost81** [comment]
@rhedman Should work if you add it to your applications main package.json like: 

"devDependencies": {
    "grunt-contrib-imagemin": "1.0.0",
    "vinyl-fs": "2.2.1",
    all other dependencies...
  }

**Comment by lylejohnson** [comment]
+1

**Comment by DariusElphickWW** [comment]
+1 from me. Trying @Everlost81's hotfix now

**Comment by lylejohnson** [comment]
Confirmed that with NodeJS 4.2.3 and npm 3.5.3, adding the "vinyl-fs": "2.2.1" dependency to your main package.json fixes this (for me).

**Comment by deepakc** [comment]
+1

**Comment by jivinivan** [comment]
:+1: Worked after upgrading npm and adding "vinyl-fs": "2.2.1". Thanks @lylejohnson and @Everlost81!

**Comment by benurb** [comment]
If adding `vinyl-fs` as a dependency doesn't work for anyone there are two other solutions in #208.
I already create a PR in vinyl-fs (https://github.com/gulpjs/vinyl-fs/pull/142)

**Comment by behr328** [comment]
+1 Getting the same issue on v1.0.0, even after upgrading. I got the same issue on v0.9.4, and upgrading to v1.0.0 fixed it, but here it is again :( Node really needs to do away with semver ranges, I expect we'll be seeing a "Semver Ranges Considered Harmful " article published in the near future..

**Comment by njd0523** [comment]
+1

**Comment by danghy** [comment]
+1

**Comment by darrennolan** [comment]
Thank you @squirrelito - same issue today.  Forcing the version for vinyl-fs in our project resolved this particular issue.

**Comment by rhedman** [comment]
@Everlost81 Forcing vinyl-fs in my main package.json now and that seems to have solved it on the build server as well :)

**Comment by MatthiasLohr** [comment]
+1

**Comment by GPif** [comment]
Same issue for me. The @Everlost81 fix worked as well.

**Comment by MatthiasLohr** [comment]
There's also a stackoverflow question for that: http://stackoverflow.com/questions/34755753/grunt-imagemin-error-cannot-read-property-contents-of-undefined

**Comment by benurb** [comment]
I also created an issue on the imagemin repository asking them if they want to pin the vinyl-fs version to 2.2.x until there is a decision on vinyl-fs' side how to proceed.
https://github.com/imagemin/imagemin/issues/147

**Comment by iamfrontender** [comment]
+1

**Comment by toptalo** [comment]
+1

**Comment by tomverran** [comment]
Thanks for the fix, sorry about the accidental PR link!

**Comment by iulo** [comment]
+1

**Comment by jsatk** [comment]
+1 same

**Comment by iulo** [comment]
I also `npm install vinyl-fs@2.2.1 --save-dev` in my local, and it work well now

**Comment by phated** [comment]
I just released vinyl-fs version 2.3.1 with fixes for this.  I ran it against this modules test suite and everything seems to be working again.  Sorry for introducing a regression in the dependency chain.

**Comment by jsatk** [comment]
@phated does this mean that I can remove my newly added `vinyl-fs` from my `package.json` (I added it strictly to solve this issue) and simply run `npm update` and things should work?

**Comment by phated** [comment]
@jsatk yes, that is exactly what it means

**Comment by jsatk** [comment]
Thanks @phated! Much appreciated.

**Comment by toptalo** [comment]
@phated :+1:

**Comment by Everlost81** [comment]
@phated Thanks for getting this sorted and sorry about the slow response. Closing the issue.
