### ISSUE TITLE
Fatal error: travis-ci build Cannot read property 'contents' of undefined

### ISSUE THREAD

**Issue by anbestephen** [gruntjs/grunt-contrib-imagemin#345]
this is similar to #330. here is [travis-ci build-log](https://travis-ci.org/raeprojects/www-raeprojects-org/builds/102134336) and [my repository](https://github.com/raeprojects/www-raeprojects-org). I am able to build locally , but i can't succeed travis-ci build. Can any one look at this?

**Comment by FellowHobbyist** [comment]
I am encountering the same issue with my travis-ci build for an Angular + Firebase Application...

Gruntfile.js defines the task
```
imagemin: {
      dist: {
        files: [{
          expand: true,
          cwd: '<%= yeoman.app %>/images',
          src: '{,*/}*.{png,jpg,jpeg,gif}',
          dest: '<%= yeoman.dist %>/images'
        }]
      }
    },
```

grunt build completes successfully locally... 

```
Running "imagemin:dist" (imagemin) task
    Minified 9 images (saved 77.32 kB)
    
    Done, without errors.
    
    Execution Time (2016-01-13 17:04:49 UTC)
    imagemin:dist  1.6s  100%
    Total 1.6s
```

grunt build errors out via travis-ci... 
```
Warning: Running "imagemin:dist" (imagemin) task
    Fatal error: Cannot read property 'contents' of undefined
    
    
    Execution Time (2016-01-13 17:00:32 UTC)
    loading tasks    9ms   2%
    imagemin:dist  441ms  98%
    Total 450ms Use --force to continue.
        
        Aborted due to warnings.
```

I have tried to determine if there is a syntax issue in how I am declaring src in the task... however, that does not appear to be the case... as I can successfully complete the build locally without error using multiple combinations, including the example provided by Grunt for grunt-contrib-imagemin

Ref:  https://github.com/gruntjs/grunt-contrib-imagemin

Any thoughts or suggestions?

**Comment by FellowHobbyist** [comment]
As a follow-up... I have successfully moved passed this issue by swapping out "grunt-contrib-imagemin": "^1.0.0" for "grunt-image": "^1.2.1" ... and subsequently updating my Gruntfile.js by replacing imagemin tasks with image tasks... 

Local builds and Travis builds are now succeeding with the same results.  

Gruntfile.js
```
image: {
      dist: {
        files: [{
          expand: true,
          cwd: '<%= yeoman.app %>/images',
          src: '{,*/}*.{png,jpg,jpeg,gif}',
          dest: '<%= yeoman.dist %>/images'
        }]
      }
    },
```

Sample build output below:

```
    Running "image:dist" (image) task
    ✔ app/images/npmjs.png -> before=3.75 kB after=158 B reduced=3.59 kB(95.9%)
    ✔ app/images/bootstrap.png -> before=41.5 kB after=21.93 kB reduced=19.57 kB(47.2%)
    ✔ app/images/bowerjs.png -> before=17.71 kB after=6.65 kB reduced=11.06 kB(62.5%)
    ✔ app/images/nodejs.png -> before=8.45 kB after=2.93 kB reduced=5.51 kB(65.3%)
    ✔ app/images/starterlog.png -> before=34.53 kB after=10.58 kB reduced=23.95 kB(69.3%)
    ✔ app/images/gruntjs.png -> before=84.38 kB after=27.98 kB reduced=56.4 kB(66.8%)
    ✔ app/images/firebase.png -> before=32.03 kB after=12.19 kB reduced=19.83 kB(61.9%)
    ✔ app/images/fontawesome.png -> before=12.01 kB after=5.63 kB reduced=6.38 kB(53.1%)
    ✔ app/images/angular.png -> before=41.5 kB after=18.63 kB reduced=22.87 kB(55.1%)
    
    Done, without errors.
    
    Execution Time (2016-01-13 17:47:44 UTC)
    image:dist  2.6s  99%
    Total 2.6s
```

**Comment by anbestephen** [comment]
it works :+1:  !!!! after removing "^" when specifying a version of vinyl-fs in package.json file , it builds successfully with this [build-log](https://travis-ci.org/raeprojects/www-raeprojects-org/builds/102158965). Thanks @juliusosokinas , @lorijoan , @ernestorocha , @FellowHobbyist  and everybody else.

**Comment by anbestephen** [comment]
I am closing this issue now!
