### ISSUE TITLE
a bug(version: 1.0.0)

### ISSUE THREAD

**Issue by suwenxiong** [gruntjs/grunt-contrib-imagemin#347]
node_modules/grunt-contrib-imagemin/tasks/imagemin.js
61line:     var diffSize = origSize - data[0].contents.length;
it can't run

fiexed:
change: var diffSize = data.length ? (origSize - data[0].contents.length) : 0;

**Comment by phated** [comment]
Ref https://github.com/gruntjs/grunt-contrib-imagemin/issues/344#issuecomment-171582523 - should be fixed with the vinyl-fs 2.3.1 release I just published.  Make sure to update your dependencies completely.

**Comment by suwenxiong** [comment]
thank you very much!

**Comment by steveoh** [comment]
close this?
