### ISSUE TITLE
use plugins

### ISSUE THREAD

**Issue by rkgttr** [gruntjs/grunt-contrib-imagemin#349]
Hi,

Tried to use some plugins (pngquant and mozjpeg) with grunt-contrib-imagemin

`var mozjpeg = require( 'imagemin-mozjpeg' );`
 `var pngquant = require( 'imagemin-pngquant' );`
 [...]
`imagemin: {`
`imgs: {`
`options: {`
`use: [ pngquant( {quality: '65-80', speed: 3} ), mozjpeg() ]`
 `},`
`files: [ {`
 `expand: true,`
 `cwd: 'src/',`
`src: [ '**/img/**/*.{png,jpg,gif,svg}' ],`
 `dest: 'build/'`
`} ]`
`}`
`}`
My grunt task runs until it reaches imagemin, then it silently fails and stops. If I empty the `use` array, then it works.

Any idea why?

Thanks.

**Comment by kevva** [comment]
Probably due to `mozjpeg` failing to install on your system. There are already a number of issues open about it on the `mozjpeg` [issue tracker](https://github.com/imagemin/mozjpeg-bin/issues).
