### ISSUE TITLE
Problem when executing optipng.exe

### ISSUE THREAD

**Issue by Meranuxapb** [gruntjs/grunt-contrib-imagemin#350]
That's meaasage in my console. Win 7, node v 5.6.0.
Warning: Error: Command failed: D:...\node_modules\optipng-bin\vendor\optipng.exe -strip all -clobber -force -fix -o 2 -out C:\Users\Toxa\AppData\Local\Temp\f8f63803-ceae-4806-a6c0-47ddfd67828e C:\Users\User\AppData\Local\Temp\a56f98f3-4e0c-4e70-b77b-e5eb35bb7122
*\* Processing: C:\Users\User\AppData\Local\Temp\a56f98f3-4e0c-4e70-b77b-e5eb35bb7122
575x575 pixels, 4x8 bits/pixel, RGB+alpha
Stripping metadata...
Input IDAT size = 84898 bytes
Input file size = 85062 bytes

Trying:
  zc = 9  zm = 8  zs = 0  f = 0         IDAT size = 68909
 in file web/img/jupiter.png Use --force to continue.
What can be happend?

**Comment by konstantin24121** [comment]
+

**Comment by RayFoss** [comment]
Now there seems to be a dependency on https://github.com/imagemin/optipng-bin that's not working for me on Fedora/RHEL but that seems to be another issue all together.

**Comment by blowsie** [comment]
Same issue for me

**Comment by blowsie** [comment]
**Referencing**
https://github.com/gruntjs/grunt-contrib-imagemin/issues/348
https://github.com/gruntjs/grunt-contrib-imagemin/issues/360
https://github.com/gruntjs/grunt-contrib-imagemin/issues/350

**Comment by sindresorhus** [comment]
Closing to clean up the issue tracker. If this is still an issue, open an issue on the relevant Imagemin plugin/binary repo instead.
