### ISSUE TITLE
Bug running task in a folder with parentheses

### ISSUE THREAD

**Issue by rdourado** [gruntjs/grunt-contrib-imagemin#351]
When a folder name has parentheses, the full path from source is copied to dest folder. Example:

Considering this folder structure:

```
/optimize(images)/
    /compressed/
    /img/2015/10/image.png
    Gruntfile.js
    package.json
```

And this task:

``` javascript
imagemin: {
    png: {
        options: {optimizationLevel: 7},
        files: [{
            expand: true,
            cwd: 'img',
            src: ['**/*.png'],
            dest: 'compressed',
            ext: '.png'
        }]
    }}
```

This is the result:

```
/optimize(images)/
    /compressed/2015/10/optimize(images)/img/2015/10/image.png
    /img/2015/10/image.png
    Gruntfile.js
    package.json
```

The final image is in fact optimized, the problem is just with the result folder path.
BTW, this problem is happening with me because my files are in a Dropbox folder named “Dropbox (Personal)”. I've tried creating a symbolic link with a different name, but the result was the same.

**Comment by ThomasChan** [comment]
+1

**Comment by yuzeh** [comment]
+1

**Comment by yuzeh** [comment]
This looks to be a bug with imagemin. I've filed a bug there: https://github.com/imagemin/imagemin/issues/156

**Comment by AurelioDeRosa** [comment]
This bug might be fixed in version 5 but this package installs version 4.

**Comment by kevva** [comment]
In `imagemin@4.x.x`, we're just using [`vinyl-fs`](https://github.com/gulpjs/vinyl-fs) to read and write the files, so it might have something to do with it.

**Comment by stephanfriedrich** [comment]
Hi @all, i had the same problem, an created an work around. Maybe it helps someone.

here we run imagemin-cli (or imagemin-newer) to imagemin-temporary-directory, copy everything with grunt-copy (in my case for crossOS reasons) into the origin-image-source, and remove imagemin-temporary-directory.

update package.json

```
...
  "devDependencies": {
    "grunt-contrib-copy": "^0.6.0",
    "grunt-shell": "^1.3.0",
    "imagemin": "latest",
    "imagemin-newer": "^1.0.1",
  },
  "scripts": {
    "imagemin_script_1": "imagemin-newer <source-dir-1> <destination-dir-temp1> -d".
    "imagemin_script_2": "imagemin-newer <source-dir-2> <destination-dir-temp2> -d"
  },
...
```

update gruntfile.js

```
...
    shell: {
      options: {
        stderr: false
      },
      imagemin: {
        command: [
          'npm run imagemin_script_1'
          'npm run imagemin_script_2'
        ].join('&&')
      },
      removeImageminTmp: {
        command:  [
          'rm -rf <source-dir-1>'
          'rm -rf <source-dir-2>'
        ].join('&&')
      }
    },
    copy: {
      imageminCssImages: {
        files: [{
          expand: true,
          flatten: true,
          src: ''source-dir-temp1/**/*.{png,gif,jpg,svg,ico}',
          dest: 'build/assets/img'
        }]
      },
      imageminHtmlImages: {
        files: [{
          expand: true,
          flatten: true,
          src: ''source-dir-temp2/**/*.{png,gif,jpg,svg,ico}',
          dest: 'build/img'
        }]
      }
    },
...
```
```
...
  grunt.loadNpmTasks('grunt-shell');
  grunt.loadNpmTasks('grunt-contrib-copy');

  grunt.registerTask('test', [
    'shell:imagemin',
    'copy',
    'shell:removeImageminTmp',
  ]);
...
```

**Comment by C-Duv** [comment]
Thanks for sharing, I was becoming insane not understanding why sub-directories named per parent directories where being created...

**Comment by kevva** [comment]
Can you try out `2.0.0`? If the issue still persists I'll reopen.
