### ISSUE TITLE
Is there a way to compress the images only once per build?

### ISSUE THREAD

**Issue by RobertBaron** [gruntjs/grunt-contrib-imagemin#353]
Let's say we compress the images, but we don't want to compress images everytime we build the app, we want to compress only if there are difference not always.
I am thinking to get the differences between the not compressed and compressed folders and just compress the difference, but anyway may be someone has a better solution and also, this can be a feature for the package.

Thanks :)

**Comment by vlrprbttst** [comment]
maybe try with grunt newer? https://github.com/tschaub/grunt-newer

**Comment by sindresorhus** [comment]
:arrow_up:
