### ISSUE TITLE
if images don't need to be optimized, they stay in the source directory

### ISSUE THREAD

**Issue by vlrprbttst** [gruntjs/grunt-contrib-imagemin#356]
I've just noticed this on a project I'm working on:

say you have tons of images to compress and they sit in an `images-src` folder. once compressed, they go in an `images` folder and these are the ones you use in your project.

it can happen that some images don't need any optimization and I've noticed they stay in the source folder and don't move in `images` but that poses a problem because now, some images are missing and I don't even know exactly which ones.

is this a bug or am i missing something?

my configuration is pretty straight forward:

```
        imagemin: {
            dynamic: {
                files: [{
                    expand: true, // Enable dynamic expansion
                    cwd: '_src/images/', // source images (not compressed)
                    src: ['**/*.{png,jpg,gif,svg}'], // Actual patterns to match
                    dest: '_dev/images/' // Destination of compressed files
                }]
            }
        }, //end imagemin
```

**Comment by kevva** [comment]
This should be fixed in `2.0.0`.
