### ISSUE TITLE
Getting dynamic image paths to work with a custom optimizationLevel

### ISSUE THREAD

**Issue by florian** [gruntjs/grunt-contrib-imagemin#357]
I'm sorry if I just made some trivial mistake in the config but I can't get dynamic image paths to work with a custom `optimizationLevel`.

This is my config:

``` js
    imagemin: {
      dynamic: {
        options: {
          optimizationLevel: 7
        },

        files: [{
          expand: true,
          cwd: '.',
          src: ['img/**/*.png'],
          dest: 'dist/'
        }]
      }
    }
```

It works in general, but it ignores the `optimizationLevel`. I tried to use `options` just like in the example for [static](https://github.com/gruntjs/grunt-contrib-imagemin/blob/master/docs/imagemin-examples.md#example-config) image paths.

Is this a problem with this grunt plugin or did I just make a mistake in the config?

**Comment by florian** [comment]
I also tried changing the source code of this plugin [here](https://github.com/gruntjs/grunt-contrib-imagemin/blob/master/tasks/imagemin.js#L26) and it didn't have any effect when changing the level to 7. Maybe the options are not passed correctly to the PNG minifier…

**Comment by kevva** [comment]
Can you try out `2.0.0`? If the issue still persists I'll reopen.
