### ISSUE TITLE
Warning: Cannot read property 'charCodeAt' of undefined

### ISSUE THREAD

**Issue by mrmartineau** [gruntjs/grunt-contrib-imagemin#358]
I am suddenly seeing this error when I run the imagemin task:

> Warning: Cannot read property 'charCodeAt' of undefined Use --force to continue.

Here's my config:

``` js
var pngquant = require('imagemin-pngquant');
var mozjpeg = require('imagemin-mozjpeg');

module.exports.tasks = {

    /**
     * grunt-contrib-imagemin
     * https://github.com/gruntjs/grunt-contrib-imagemin
     * Minify PNG, SVG, gif & JPEG images
     */
    imagemin: {
        images: {
            options: {
                optimizationLevel: 3,
                progressive: true,
                use: [
                    pngquant({ quality: '40-50', speed: 4 }),
                    mozjpeg({ quality: 70 }),
                ],
            },

            files: [{
                expand: true,
                cwd: 'assets/src/img',
                src: ['**/*.{svg,png,jpg,gif}'],
                dest: 'assets/dist/img',
            }],
        },
    },
};
```

I am using the latest version of the plugin and node 5.10.1. Has anyone else experienced this issue?

**Comment by mrmartineau** [comment]
Does anyone have any ideas about this?

**Comment by hiulit** [comment]
Same issue here

**Comment by Fanus** [comment]
Got same issue. Is there a temporary workaround perhaps?

**Comment by mrmartineau** [comment]
@hiulit for what its worth, I have reverted back to older versions of my imagemin plugins.

**Comment by dimafeldman** [comment]
I have the same issue - anything changed since the last comment?

**Comment by tony2nite** [comment]
As per @mrmartineau suggestion, these package versions work for me.
```    
"imagemin-gifsicle": "^4.1.0",
"imagemin-mozjpeg": "^5.1.0",
"imagemin-optipng": "^4.1.0",
"imagemin-svgo": "^4.1.0",
```

It seems if you only add one file type e.g. `src: ['**/*.{png}']` for the `src` the problem goes away, so maybe something to do with supporting this format. But using only one filetype obviously defeats the purpose of `expand`.

**Comment by chenEdgar** [comment]
I have the same problem when I used the latest one to minify the image. node version is 5.9.0

**Comment by M4Gd** [comment]
I am in the same boat. Any suggestion?

**Comment by cz848** [comment]
Got same issue. Any suggestion?

**Comment by mrmartineau** [comment]
@M4Gd & @cz848 see [my comment](https://github.com/gruntjs/grunt-contrib-imagemin/issues/358#issuecomment-221006927) and @tony2nite's [code](https://github.com/gruntjs/grunt-contrib-imagemin/issues/358#issuecomment-224828487) above for a fix. I still use this fix for my build to work, hopefully a fix will be found soon

**Comment by mfowlewebs** [comment]
Running with `--stack` reports:

```
TypeError: Cannot read property 'charCodeAt' of undefined
    at isBinary (/home/mfowle/src/tower/core/node_modules/imagemin-svgo/node_modules/is-svg/index.js:8:38)
    at module.exports (/home/mfowle/src/tower/core/node_modules/imagemin-svgo/node_modules/is-svg/index.js:19:10)
    at buf (/home/mfowle/src/tower/core/node_modules/imagemin-svgo/index.js:8:7)
    at Imagemin.use (/home/mfowle/src/tower/core/node_modules/imagemin/index.js:63:51)
    at /home/mfowle/src/tower/core/node_modules/grunt-contrib-imagemin/tasks/imagemin.js:38:18
    at /home/mfowle/src/tower/core/node_modules/async/lib/async.js:181:20
    at replenish (/home/mfowle/src/tower/core/node_modules/async/lib/async.js:319:21)
    at /home/mfowle/src/tower/core/node_modules/async/lib/async.js:330:15
    at Object.async.forEachLimit.async.eachLimit (/home/mfowle/src/tower/core/node_modules/async/lib/async.js:220:35)
    at Object.<anonymous> (/home/mfowle/src/tower/core/node_modules/grunt-contrib-imagemin/tasks/imagemin.js:30:15)
```

Something around the is-svg module then.

**Comment by kevva** [comment]
Can you try out `2.0.0`? If you get the same error, open an issue at `is-svg` with the failing image.
