### ISSUE TITLE
Error: spawn … ENOENT when it's a sub-dependency

### ISSUE THREAD

**Issue by ryuran** [gruntjs/grunt-contrib-imagemin#360]
Hello

I have a project with grunt-contrib-imagemin@1.0.0 as dependency.
When I run grunt imagemin:build inside, everything is OK.

But when my project is a dependency of another one, the install task fail on it.

```
Running "imagemin:build" (imagemin) task
Warning: Error: spawn …/test2/node_modules/optipng-bin/vendor/optipng ENOENT in file src/img/xxx.png Use --force to continue.
```

I test it on 2 different environnement and node 4.4.4
Can be from optipng.
Can be linked to #348 .

Thanks for help

**Comment by ryuran** [comment]
Seems to be from NPM https://github.com/npm/npm/issues/12644

**Comment by blowsie** [comment]
**Referencing**
https://github.com/gruntjs/grunt-contrib-imagemin/issues/348
https://github.com/gruntjs/grunt-contrib-imagemin/issues/360
https://github.com/gruntjs/grunt-contrib-imagemin/issues/350

**Comment by geoffdavis92** [comment]
@ryuran if you're still having this problem, try reinstalling all node modules a la [this comment](https://stackoverflow.com/a/31171785/5641437). 

Worked for me

**Comment by ryuran** [comment]
Since this issue I stop to use grunt. @geoffdavis92

**Comment by sindresorhus** [comment]
Closing to clean up the issue tracker. If this is still an issue, open an issue on the relevant Imagemin plugin/binary repo instead.
