### ISSUE TITLE
Unable to install npm in Windows 7

### ISSUE THREAD

**Issue by 972969** [gruntjs/grunt-contrib-imagemin#362]
C:\>npm install -g
npm ERR! addLocal Could not install C:\
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "install" "-g"
npm ERR! node v4.4.4
npm ERR! npm  v2.15.1
npm ERR! code EISDIR
npm ERR! errno -4068
npm ERR! syscall read

npm ERR! eisdir EISDIR: illegal operation on a directory, read
npm ERR! eisdir This is most likely not a problem with npm itself
npm ERR! eisdir and is related to npm not being able to find a package.json in
npm ERR! eisdir a package you are trying to install.
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "install" "-g"
npm ERR! node v4.4.4
npm ERR! npm  v2.15.1
npm ERR! path C:\npm-debug.log.2315540811
npm ERR! code EPERM
npm ERR! errno -4048
npm ERR! syscall open

npm ERR! Error: EPERM: operation not permitted, open 'C:\npm-debug.log.231554081
1'
npm ERR!     at Error (native)
npm ERR!  { [Error: EPERM: operation not permitted, open 'C:\npm-debug.log.23155
40811']
npm ERR!   errno: -4048,
npm ERR!   code: 'EPERM',
npm ERR!   syscall: 'open',
npm ERR!   path: 'C:\\npm-debug.log.2315540811' }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\npm-debug.log

**Comment by kevva** [comment]
Running `npm install -g` inside `C:\` won't work and is certainly not a problem with this module.
