### ISSUE TITLE
Error: write EOF in file image.jpg

### ISSUE THREAD

**Issue by Kamilius** [gruntjs/grunt-contrib-imagemin#364]
The thing is, I'm trying to minify jpg, and gif files. There is one file which requires "--force" flag to relatively succeed - *.jpg. The message it throws - "Warning: Error: write EOF in file buid/styles/Images/body_background.jpg Use --force to continue.":

![epf](https://cloud.githubusercontent.com/assets/3115794/15456012/4876b1de-206c-11e6-9a1a-8b8191c8b728.png)

When placing "--force" tag, rest of files processed successfuly.

Environment: Win10.
My grunt task configuration:

``` js
   imagemin: {
      release: {
        files: [{
          expand: true,
          src: 'build/**/*.{jpg,gif,png}',
        }],
        options: {
          progressive: true, // progressive jpgs
        },
      },
    },
```

Any clue on how to fix this, and maybe a reasons of such behavior?

Thanks

**Comment by visualjazz-sbrunno** [comment]
I had the same error, i just re-saved that image in photoshop with 'Save for web' and that fixed the issue for me in the meantime.

**Comment by sindresorhus** [comment]
Closing to clean up the issue tracker. If this is still an issue, open an issue on the relevant Imagemin plugin/binary repo instead.
