### ISSUE TITLE
Duplicates folder on Dropbox

### ISSUE THREAD

**Issue by humso** [gruntjs/grunt-contrib-imagemin#366]
I've my project folder on dropbox. When running "grunt imagemin" it successfully minifies the image from the source folder but it creates a duplicate root folder inside the destination folder. This issue didn't exist on previous versions of imagemin i.e "grunt-contrib-imagemin": "~0.8.1" which I'm using exactly the same code.

`imagemin: {
        dist: {
          files: [{
            expand: true,
            cwd: 'src/images',
            src: ['**/*.{png,jpg,gif}'],
            dest: 'dist/assets'
          }]
        }
      },`

![untitled-1](https://cloud.githubusercontent.com/assets/1059669/17401793/78809e3e-5a47-11e6-9e29-27bc7bea89c6.jpg)

**Comment by kevva** [comment]
Can you try out `2.0.0`? If the issue still persists I'll reopen.
