### ISSUE TITLE
imagemin 5

### ISSUE THREAD

**Issue by jorrit** [gruntjs/grunt-contrib-imagemin#367]
Is any effort going on to move to imagemin v5? The interface has changed completely so the grunt plugin needs to be rewritten almost completely. Afaik imagemin no longer includes jpegtran, gifsicle, optipng and svgo so it has to be decided if grunt-contrib-imagemin users will have to be forced to install and configure all minifiers themselves or the plugin will depend on them.

**Comment by jorrit** [comment]
@kevva , @sindresorhus any input?

**Comment by aberonni** [comment]
+1

**Comment by sindresorhus** [comment]
Fixed by https://github.com/gruntjs/grunt-contrib-imagemin/commit/65ff84e1cea21456ac0ab2db1c73c09416971667
