### ISSUE TITLE
Fatal error: spawn EACCES

### ISSUE THREAD

**Issue by kyma** [gruntjs/grunt-contrib-imagemin#374]
This seems to be happening again. 
OSX Sierra
Node 7.6.0
"grunt-contrib-imagemin": "^1.0.1"

```
imagemin: {
            dynamic: {
                options: {                      
                    optimizationLevel: 3
                },
                files: [{
                    expand: true,
                    cwd: 'app/images',
                    src: ['**/*.{png,jpg,gif}'],
                    dest: 'dist/'
                }]
            }

        },
```

**Comment by geoffdavis92** [comment]
@kyma try reinstalling all `node_modules`, per this [SO comment](https://stackoverflow.com/a/31171785/5641437)

**Comment by sindresorhus** [comment]
Closing to clean up the issue tracker. If this is still an issue, open an issue on the relevant Imagemin plugin/binary repo instead.

**Comment by jeremy-leys** [comment]
The easiest way that I can see is to delete **node_modules/** folder and execute 
$ npm install
