### ISSUE TITLE
Update project description line on GitHub

### ISSUE THREAD

**Issue by coliff** [gruntjs/grunt-contrib-imagemin#384]
Right now it states:
> Minify PNG and JPEG images

I suggest it could be updated to:
> Minify PNG, JPG, GIF and SVG images

Also, the URL could be updated from http://gruntjs.com to https://gruntjs.com

**Comment by vladikoff** [comment]
👍

**Comment by coliff** [comment]
cool thanks, you could update the URL too to save a redirect; http://gruntjs.com to https://gruntjs.com
