### ISSUE TITLE
Replace gulp-util

### ISSUE THREAD

**Issue by cmpaul** [gruntjs/grunt-contrib-imagemin#387]
`gulp-util` is deprecated:

https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5

Remove gulp-util using the following API replacements:

* gutil.File => https://www.npmjs.com/package/vinyl
* gutil.replaceExtension => The .extname property on Vinyl objects or https://www.npmjs.com/package/replace-ext
* gutil.colors => https://www.npmjs.com/package/ansi-colors
* gutil.date => https://www.npmjs.com/package/date-format
* gutil.log => https://www.npmjs.com/package/fancy-log
* gutil.template => https://www.npmjs.com/package/lodash.template
* gutil.env => https://www.npmjs.com/package/minimist
* gutil.beep => https://www.npmjs.com/package/beeper
* gutil.noop => https://www.npmjs.com/package/through2
* gutil.isStream => Use the .isStream() method on Vinyl objects
* gutil.isBuffer => Use the .isBuffer() method on Vinyl objects
* gutil.isNull => Use the .isNull() method on Vinyl objects
* gutil.linefeed => Use the string '\n' in your code
* gutil.combine => https://www.npmjs.com/package/multipipe
* gutil.buffer => https://www.npmjs.com/package/list-stream
* gutil.PluginError => https://www.npmjs.com/package/plugin-error

**Comment by XhmikosR** [comment]
Nothing we can do, because this comes from:

```
C:\Users\xmr\Desktop\grunt\grunt-contrib-imagemin>npm ls gulp-util
grunt-contrib-imagemin@2.0.1 C:\Users\xmr\Desktop\grunt\grunt-contrib-imagemin
`-- imagemin-gifsicle@5.2.0
  `-- gifsicle@3.0.4
    `-- bin-build@2.2.0
      `-- download@4.4.3
        `-- gulp-decompress@1.2.0
          `-- gulp-util@3.0.8
```

**Comment by cmpaul** [comment]
Doh!
