### ISSUE TITLE
Duplicating images with period in file name

### ISSUE THREAD

**Issue by qasimalyas** [gruntjs/grunt-contrib-imagemin#42]
I'm using grunt-contrib-imagemin plugin to optimise some images in a directory. 

The idea is that imagemin should compress the existing images and NOT create duplicate ones with different names.

For some reason any images which have a period will be duplicated with a different name (name before first period), for example:
- sprite.buttons.png --> sprite.png
- register.online.png --> register.png

The code that I am using within gruntConfig is:

```
imagemin: {
  dynamic_mappings: {
    files: [
      {
        expand: true,
        cwd: 'assets/graphics/',
        src: ['**/*.png'],
        dest: 'assets/graphics/',
        ext: '.png'
      }
    ]
  }
}
```

What can I do to overcome this issue?

**Comment by phoenixdev-kl** [comment]
Had the same issue like you, qasimalyas. What did it for me: adding `extDot: 'last'` to my config. So it looks now like:

```
...
        files: [{
            expand: true,
            src: ['**/*.png'],
            ext: '.png',
            extDot: 'last'
        }]
...
```

**Comment by qasimalyas** [comment]
@phoenixdev-kl yea i've known about this since they introduced the change in grunt. Thanks
