### ISSUE TITLE
"Fatal error: spawn ENOENT" in  win7 64bit  

### ISSUE THREAD

**Issue by vizonluo** [gruntjs/grunt-contrib-imagemin#61]
config like this: 

``` js
imagemin: {
      build: {
        src: 'img/npm.png',
        dest: 'imgmin/npm.png'
    }
}
```

**Comment by KimmoCommit** [comment]
I know this is a tad old one, but my fix was just deleting node_modules and installing them back with npm install. 

I think there might be some correlation with the fact that when deleting the modules folder, it said to contain files that had names too long to be put to Windows trash, thus they needed to be deleted permanently.

P.S   my  "grunt-contrib-imagemin" version is  "~0.7.1",
