### ISSUE TITLE
Error: spawn ENOENT when running imagemin task

### ISSUE THREAD

**Issue by msguerra74** [gruntjs/grunt-contrib-imagemin#96]
I'm getting the following error when running imagemin. I'm not sure why, but it looks like it's adding a tmp folder inside the 'grunt-jekyll' task? I've tried running it independent of any other task and the same error occurs. After crashing, it leaves some of the images in the output folder with '.tmp' extensions (ex: image.png.tmp). Any ideas would be greatly appreciated, thanks!

```
Running "imagemin:images" (imagemin) task

D:\Dropbox\Projects\automata\node_modules\grunt-jekyll\node_modules\tmp\lib\tmp.js:261
  throw err;
        ^
Error: spawn ENOENT
  at errnoException (child_process.js:980:11)
  at Process.ChildProcess._handle.onexit (child_process.js:771:34)
```

**Comment by nottinhill** [comment]
This is latest Mac Yosemite. Installed imagemin as well as pngquant latest version. Not working, failing with error message provided by the thread creator.

**Comment by SamJacobs** [comment]
Installing earlier version of contrib-imagemin fixed it for me. I picked one at random. used 0.4.0, grunt build worked

**Comment by jzaric** [comment]
@SamJacobs Worked for me. I was using 0.8.0 and it started working when I installed 0.7.0

**Comment by binarykitchen** [comment]
Okay, I found out when this is happening: when the prebuild-test failed and thus is compiling from the source, see extract below:

```
  ⚠ Couldn't connect to https://raw.github.com/imagemin/optipng-bin/v2.0.4/vendor/linux/x64/optipng (503)
  ⚠ optipng pre-build test failed
  ℹ compiling from source
  ✖ Error: ./configure --with-system-zlib --prefix="/var/www/signdna-video/live/source/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/imagemin-optipng/node_modules/optipng-bin/vendor" --bindir="/var/www/signdna-video/live/source/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/imagemin-optipng/node_modules/optipng-bin/vendor" && make install
Command failed: 
    at ChildProcess.exithandler (child_process.js:648:15)
    at ChildProcess.emit (events.js:98:17)
    at maybeClose (child_process.js:756:16)
    at Socket.<anonymous> (child_process.js:969:11)
    at Socket.emit (events.js:95:17)
    at Pipe.close (net.js:465:12)
```

This happened during instable network conditions which is not the real issue here. The problem is that compiling from source results in a different state than when doing the pre-build. Both ways should make the code behave the same.

**Comment by schmod** [comment]
I'm having a similar issue with jpegtran failing to build, likely due to Github's network problems...

The real underlying issue seems to be that optipng and jpegtran's build scripts can fail "silently," without cascading upwards to imagemin/grunt-imagemin.

**Comment by schmod** [comment]
I've opened a [PR](https://github.com/imagemin/jpegtran-bin/pull/58) in `jpegtran-bin` that will hopefully cause compilation errors to propogate upward, so that the NPM module doesn't trick any dependent packages into believing that it was installed successfully.

**Comment by kevva** [comment]
@schmod, that's exactly what we want. They are optional dependencies.

**Comment by schmod** [comment]
I left a comment in the other thread.  

Essentially, I don't think that's actually a desirable behavior, as it bypasses npm's built-in infrastructure for handling optional dependencies, and effectively makes `imagemin` and `grunt-contrib-imagemin` unsafe to use in a scripted environment, as it doesn't provide any reliable mechanism to determine whether or not everything installed correctly.  

`imagemin` already has logic to gracefully treat `jpegtran-bin` as an optional dependency, but that logic is worthless if `jpegtran-bin`'s build script doesn't report failures.

**Comment by kevva** [comment]
What about the people that's trying to install something that has imagemin as a dependency but can't get a module working? They will never be able to install their stuff.

**Comment by patternboxtech** [comment]
Ran into this issue with "grunt-contrib-imagemin": "^0.8.1".  Updated to "grunt-contrib-imagemin": "^0.9.4" fixed my issue.

**Comment by sbley** [comment]
Updating "grunt-contrib-imagemin" from "^0.9.2" to "^0.9.4" fixed my issue.
